### ISSUE TITLE
Make sure to provide either `input_features` or `encoder_outputs` to `generate`

### ISSUE THREAD

**Issue by crush119** [SWivid/F5-TTS#101]
Traceback (most recent call last):
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\gradio\queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\gradio\blocks.py", line 2016, in process_api
    result = await self.call_function(
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\gradio\blocks.py", line 1569, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\谦以自强\F5-TTS\gradio_app.py", line 326, in infer
    ref_text = pipe(
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 284, in __call__
    return super().__call__(inputs, **kwargs)
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\transformers\pipelines\base.py", line 1260, in __call__
    return next(
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\transformers\pipelines\pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\transformers\pipelines\pt_utils.py", line 269, in __next__
    processed = self.infer(next(self.iterator), **self.params)
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\transformers\pipelines\base.py", line 1175, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 512, in _forward
    tokens = self.model.generate(
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\transformers\models\whisper\generation_whisper.py", line 507, in generate
    batch_size, total_input_frames = self._retrieve_total_input_frames(
  File "D:\Aniconda\envs\f5-tts\lib\site-packages\transformers\models\whisper\generation_whisper.py", line 1126, in _retrieve_total_input_frames
    raise ValueError("Make sure to provide either `input_features` or `encoder_outputs` to `generate`.")
ValueError: Make sure to provide either `input_features` or `encoder_outputs` to `generate`.   How to solve?

**Comment by SWivid** [comment]
what is your version of gradio and transformer
and also python

**Comment by SWivid** [comment]
I'll close this issue, if you have other questions you can reopen this issue.

**Comment by zsoflo** [comment]
Hello ! I currently also have this problem. I have python 3.11.13, transformers 4.42.0, and no gradio installed.
