### ISSUE TITLE
Run time error while fine tuning

### ISSUE THREAD

**Issue by rasheed-aidetic** [SWivid/F5-TTS#145]
I am trying to fine tune the model. And I am stuck with this error 

>`Epoch 1/10:  23% 34/145 [00:24<01:21,  1.36step/s, loss=1.92, step=34]
Traceback (most recent call last):
  File "/content/F5-TTS/train.py", line 94, in <module>
    main()
  File "/content/F5-TTS/train.py", line 88, in main
    trainer.train(train_dataset,
  File "/content/F5-TTS/model/trainer.py", line 229, in train
    loss, cond, pred = self.model(mel_spec, text=text_inputs, lens=mel_lengths, noise_scheduler=self.noise_scheduler)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 820, in forward
    return model_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/operations.py", line 808, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
  File "/content/F5-TTS/model/cfm.py", line 273, in forward
    pred = self.transformer(x = φ, cond = cond, text = text, time = time, drop_audio_cond = drop_audio_cond, drop_text = drop_text)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/F5-TTS/model/backbones/unett.py", line 162, in forward
    text_embed = self.text_embed(text, seq_len, drop_text = drop_text)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/F5-TTS/model/backbones/unett.py", line 57, in forward
    text = self.text_embed(text) # b n -> b n d
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/sparse.py", line 164, in forward
    return F.embedding(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 2267, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)`

these are the inputs I am using.

target_sample_rate = 24000
n_mel_channels = 100
hop_length = 256

tokenizer = "pinyin" # 'pinyin', 'char', or 'custom'
tokenizer_path = None # if tokenizer = 'custom', define the path to the tokenizer you want to use (should be vocab.txt)
dataset_name = "My_Dataset"

# -------------------------- Training Settings -------------------------- #

exp_name = "E2TTS_Base"  # F5TTS_Base | E2TTS_Base

learning_rate = 5e-06

batch_size_per_gpu = 38400  # 8 GPUs, 8 * 38400 = 307200
batch_size_type = "frame"  # "frame" or "sample"
max_samples = 2  # max sequences per batch if use frame-wise batch_size. we set 32 for small models, 64 for base models
grad_accumulation_steps = 1  # note: updates = steps / grad_accumulation_steps
max_grad_norm = 1.

epochs = 10  # use linear decay, thus epochs control the slope
num_warmup_updates = 20  # warmup steps
save_per_updates = 500  # save checkpoint per steps
last_per_steps = 5000  # save last checkpoint per steps

Is this error something related to my dataset or my input? Can anyone help?

**Comment by ZhikangNiu** [comment]
'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)

maybe you need to check the tensor's type

**Comment by MilanaShhanukova** [comment]
@rasheed-aidetic I may guess that you have an empty text sample, check it out. If it intended, you may add the type converter in TextEmbedding

```
        if text.dtype is not torch.long:
            text = text.long()
```

**Comment by rasheed-aidetic** [comment]
Thank you so much @MilanaShhanukova
