### ISSUE TITLE
using cpu only

### ISSUE THREAD

**Issue by d3r4j** [SWivid/F5-TTS#176]
>>python gradio_app.py
Using cpu device
Starting app...
Running on local URL:  http://127.0.0.1:7878
Traceback (most recent call last):
  File "D:\tech\F5-TTS\gradio_app.py", line 792, in <module>
    main()
  File "C:\Users\dhira\.conda\envs\f5\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\dhira\.conda\envs\f5\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\dhira\.conda\envs\f5\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\dhira\.conda\envs\f5\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\tech\F5-TTS\gradio_app.py", line 785, in main
    app.queue(api_open=api).launch(
  File "C:\Users\dhira\.conda\envs\f5\lib\site-packages\gradio\blocks.py", line 2465, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

**Comment by SWivid** [comment]
Running on cpu would be much slower. 
It is recommended to try with online space demos if the device at hand does not have a GPU.

**Comment by Makkarob** [comment]
> Owner

I'm using an i3 9100f with 32GB DDR4 and have no complaints. Unless you're voicing full `Romeo and Juliet`, you should be fine.
