### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by ThinkInFuture** [SWivid/F5-TTS#177]
Traceback (most recent call last):
  File "inference-cli.py", line 19, in <module>
    from model import CFM, DiT, MMDiT, UNetT
  File "/opt/SWivid/F5-TTS/F5-TTS/model/__init__.py", line 7, in <module>
    from model.trainer import Trainer
  File "/opt/SWivid/F5-TTS/F5-TTS/model/trainer.py", line 22, in <module>
    from model.dataset import DynamicBatchSampler, collate_fn
  File "/opt/SWivid/F5-TTS/F5-TTS/model/dataset.py", line 127, in <module>
    class DynamicBatchSampler(Sampler[list[int]]):
TypeError: 'type' object is not subscriptable

**Comment by SWivid** [comment]
Thought it was for using a early python version.
Try with python least 3.9,  python>=3.10(recommended)

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions.
