### ISSUE TITLE
RuntimeError: The size of tensor a (128) must match the size of tensor b (289) at non-singleton dimension 1

### ISSUE THREAD

**Issue by sarpba** [SWivid/F5-TTS#191]
I try to test the finetune with gradio_finetune.py
A little test database:
prepare complete 
samples : 27333
time data : 27:42:51
min sec : 0.6
max sec : 38.14
file_arrow : data/hun_pinyin/raw.arrow

I got the following error at 1998 step with one rtx3090 or 999 with 2 rtx3090:

Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.397 seconds.
Prefix dict has been built successfully.
accelerate launch finetune-cli.py --exp_name F5TTS_Base --learning_rate 0.0001 --batch_size_per_gpu 3200 --batch_size_type frame --max_samples 64 --grad_accumulation_steps 1 --max_grad_norm 1 --epochs 10 --num_warmup_updates 2734 --save_per_updates 6834 --last_per_steps 34166 --dataset_name hun --finetune True
Using logger: wandb
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: arpadsantha (arpadsantha-hobby). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.5
wandb: Run data is saved locally in /home/sarpba/F5-TTS/wandb/run-20241020_211115-4n6ufg52
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run F5TTS_Base
wandb: ⭐️ View project at https://wandb.ai/arpadsantha-hobby/CFM-TTS
wandb: 🚀 View run at https://wandb.ai/arpadsantha-hobby/CFM-TTS/runs/4n6ufg52
Loading dataset ...
Sorting with sampler... if slow, check whether dataset is provided with duration: 100%|██████████████████████████████████████████████████████████████████████████| 27333/27333 [00:00<00:00, 3117838.22it/s]
Creating dynamic batches with 3200 audio frames per gpu: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 27333/27333 [00:00<00:00, 3736609.34it/s]
/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 12, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Epoch 1/10:   0%|                                                                                                                                                                | 0/3127 [00:00<?, ?step/s]/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/conv.py:306: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:84.)
  return F.conv1d(input, weight, bias, self.stride,
Epoch 1/10:  64%|████████████████████████████████████████████████████████████████████████████████▌                                             | 1998/3127 [12:04<06:49,  2.76step/s, loss=0.582, step=1998]
Traceback (most recent call last):
  File "/home/sarpba/F5-TTS/finetune-cli.py", line 108, in <module>
    main()
  File "/home/sarpba/F5-TTS/finetune-cli.py", line 102, in main
    trainer.train(train_dataset,
  File "/home/sarpba/F5-TTS/model/trainer.py", line 231, in train
    loss, cond, pred = self.model(mel_spec, text=text_inputs, lens=mel_lengths, noise_scheduler=self.noise_scheduler)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sarpba/F5-TTS/model/cfm.py", line 273, in forward
    pred = self.transformer(x = φ, cond = cond, text = text, time = time, drop_audio_cond = drop_audio_cond, drop_text = drop_text)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sarpba/F5-TTS/model/backbones/dit.py", line 139, in forward
    text_embed = self.text_embed(text, seq_len, drop_text = drop_text)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sarpba/F5-TTS/model/backbones/dit.py", line 60, in forward
    text = text + text_pos_embed
RuntimeError: The size of tensor a (128) must match the size of tensor b (289) at non-singleton dimension 1
Traceback (most recent call last):
  File "/home/sarpba/F5-TTS/finetune-cli.py", line 108, in <module>
    main()
  File "/home/sarpba/F5-TTS/finetune-cli.py", line 102, in main
    trainer.train(train_dataset,
  File "/home/sarpba/F5-TTS/model/trainer.py", line 231, in train
    loss, cond, pred = self.model(mel_spec, text=text_inputs, lens=mel_lengths, noise_scheduler=self.noise_scheduler)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sarpba/F5-TTS/model/cfm.py", line 273, in forward
    pred = self.transformer(x = φ, cond = cond, text = text, time = time, drop_audio_cond = drop_audio_cond, drop_text = drop_text)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sarpba/F5-TTS/model/backbones/dit.py", line 139, in forward
    text_embed = self.text_embed(text, seq_len, drop_text = drop_text)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sarpba/anaconda3/envs/f52/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sarpba/F5-TTS/model/backbones/dit.py", line 60, in forward
    text = text + text_pos_embed
RuntimeError: The size of tensor a (128) must match the size of tensor b (289) at non-singleton dimension 1

I test it under ubuntu22.04/24.04/win11 with python version 3.10 / 3.11 / 3.12 the error alwasy same. 
Some info form my test audio splits:
0-1s: 6 file
1-2s: 2130 file
2-3s: 8625 file
3-4s: 7562 file
4-5s: 4608 file
5-6s: 2326 file
6-7s: 1137 file
7-8s: 503 file
8-9s: 210 file
9-10s: 113 file
10-11s: 60 file
11-12s: 31 file
12-13s: 10 file
13-14s: 6 file
14-15s: 5 file
15-16s: 0 file
16-17s: 1 file
17-18s: 0 file
18-19s: 0 file
19-20s: 2 file
>20s: 4 file

I have one missing character in vocab: "ű"

I'm at a loss as to what could be wrong...

**Comment by SWivid** [comment]
ah, as it is encountered by many people, we may just add a fix.

It is for including a multi-channel audio sample in your training set.

**Comment by sarpba** [comment]
I red that commit befor opened thiis one.
Multi-channel audio sample aka stereo? Just because I checked all of the splits all in same format:
24000 Khz mono 16 bit wav.
I put the fix into the code, and unfortunately nothing changed. The finetune stoped with same error.

**Comment by SWivid** [comment]
@sarpba If that was a new issue with the non-singleton RuntimeError, might you provide the text&audio facing this error?
@ZhikangNiu will help.

**Comment by sarpba** [comment]
Here is the dataset:
https://huggingface.co/datasets/sarpba/test_dataset/tree/main

**Comment by SWivid** [comment]
Hi @sarpba , what kind of text input are you using?
It would be better to provide the specific text input for us to figure out

**Comment by sarpba** [comment]
Sorry I don't understand your question.
I created this the dataset and try to finetune with finetune_gradio.py. Just click click click... :)

**Comment by Naseem56** [comment]
Update the text_len in **model/backbones/dit.py**

```
def forward(self, text: int["b nt"], seq_len, drop_text=False):  # noqa: F722
        batch, text_len = text.shape[0], text.shape[1]
        text = text + 1  # use 0 as filler token. preprocess of batch pad -1, see list_str_to_idx()
        text = text[:, :seq_len]  # curtail if character tokens are more than the mel spec tokens
        text_len = text.shape[1]
        text = F.pad(text, (0, seq_len - text_len), value=0)
```

**Comment by sarpba** [comment]
Sems to be good now.Thank you!

**Comment by SWivid** [comment]
thanks for pointing out this bug. fixed!
will close this issue.
