### ISSUE TITLE
Ran once, then exits every time

### ISSUE THREAD

**Issue by TanvirHafiz** [SWivid/F5-TTS#210]
i was able to run the gradio once. it downloaded a bunch of stuff. but didnt do any conversion. tried it again and it failed to load the UI, gave this error

Starting app...
Running on local URL:  http://127.0.0.1:7860
Traceback (most recent call last):
  File "F:\F5-TTS\gradio_app.py", line 591, in <module>
    main()
  File "F:\F5-TTS\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "F:\F5-TTS\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "F:\F5-TTS\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\F5-TTS\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "F:\F5-TTS\gradio_app.py", line 586, in main
    app.queue(api_open=api).launch(server_name=host, server_port=port, share=share, show_api=api)
  File "F:\F5-TTS\venv\lib\site-packages\gradio\blocks.py", line 2465, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

**Comment by SWivid** [comment]
Hi @TanvirHafiz .
It's probably an issue with proxy literally. Check if vpn used.
Maybe turn off tunnel mode, or if you could reach huggingface directly, just not use proxy

**Comment by TanvirHafiz** [comment]
Didn't use proxy or any of the other stuff. No idea what's happening.
Anyway I don't forget easy way to install using pinokio. I will try that

**Comment by lpscr** [comment]
try use **gradio_app.py --share** to see if this working

**Comment by TanvirHafiz** [comment]
> @TanvirHafiz try use **gradio_app.py --share** to see if this working

this seems to work. thanks

**Comment by SWivid** [comment]
as fixed, will close this issue.
feel free to open if further questions~
