### ISSUE TITLE
Error in podcast：AttributeError: 'int' object has no attribute 'export'

### ISSUE THREAD

**Issue by yhqqxq** [SWivid/F5-TTS#219]
Traceback (most recent call last):
  File "G:\AI\AI\tool\F5-TTS\env\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "G:\AI\AI\tool\F5-TTS\env\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "G:\AI\AI\tool\F5-TTS\env\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "G:\AI\AI\tool\F5-TTS\env\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "G:\AI\AI\tool\F5-TTS\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "G:\AI\AI\tool\F5-TTS\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "G:\AI\AI\tool\F5-TTS\env\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "G:\AI\AI\tool\F5-TTS\env\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "G:\AI\AI\tool\F5-TTS\gradio_app.py", line 257, in podcast_generation
    return generate_podcast(
  File "G:\AI\AI\tool\F5-TTS\gradio_app.py", line 141, in generate_podcast
    final_podcast.export(podcast_path, format="wav")
AttributeError: 'int' object has no attribute 'export'

An error will occur when running, it seems that the type is wrong?

**Comment by SWivid** [comment]
@yhqqxq tried and it works from my side
check if you are just passing blank `Podcast Script`? Make sure you get something into it.

**Comment by SWivid** [comment]
will close as resolved
feel free to open if further questions
