### ISSUE TITLE
VRAM usage randomly spikes. Continues fine after restart.

### ISSUE THREAD

**Issue by mhenrichsen** [SWivid/F5-TTS#233]
Hi,

I'm training on a single A100. I've tried multiple batch sizes, but the same thing keeps happening. 

I usually use between 10-25% of all available GPU VRAM, and then all of the sudden it spikes to 100% and crashes.

See the latest 5 wandb runs.

https://wandb.ai/mhenrichsen/CFM-TTS?nw=nwusermhenrichsen

**Comment by SWivid** [comment]
How is the dataset constructed.
Does it contain extremely few long samples?

**Comment by mhenrichsen** [comment]
@SWivid no. It's 600ish hours of 500k samples. Nothing longer than 25 seconds.

**Comment by SWivid** [comment]
> @SWivid no. It's 600ish hours of 500k samples. Nothing longer than 25 seconds.

It's weird. The training process with 38400 frames per gpu just goes well on A100 80G for us, and it usually use 60~80G mem...

**Comment by mhenrichsen** [comment]
@SWivid do you see anything wrong here?
`accelerate launch finetune-cli.py --exp_name F5TTS_Base --learning_rate 0.00001 --batch_size_per_gpu 3500 --batch_size_type frame --max_samples 64 --grad_accumulation_steps 32 --max_grad_norm 1 --epochs 10 --num_warmup_updates 500 --save_per_updates 16000 --last_per_steps 5000 --dataset_name danish_dataset --finetune True`

**Comment by SWivid** [comment]
nothing wrong with your setting i think.
if the crash just have happened at the same training point, maybe we could see throught for data used at that specific point.
for if you are using the a100 your own or on a shared remote machine (check if conflicts of gpu resource using)

**Comment by mhenrichsen** [comment]
It's my own cloud vm. The strange thing is that it went through first epoch and then crashed in 2nd.

**Comment by kmn1024** [comment]
Just a theory... having this case:
https://github.com/SWivid/F5-TTS/blob/main/model/dataset.py#L51
means that get_frame_len (https://github.com/SWivid/F5-TTS/blob/main/model/dataset.py#L32) doesn't always match up. So it's possible for DynamicBatchSampler to sometimes exceed the frames_threshold.

Try adding the same logic to get_frame_len (`if duration > 30 or duration < 0.3: self.get_frame_len((index + 1) % len(self.data))`)?

**Comment by SWivid** [comment]
> So it's possible for DynamicBatchSampler to sometimes exceed the frames_threshold.

The `self.get_frame_len()` is intended to get duration exactly for a queried index, while `__getitem__` do calling.
If `__getitem__` encounters a sample exceeding 30s, it will only find a substitution <30s.

**Comment by mhenrichsen** [comment]
Here are the complete logs:
```
Epoch 1/10:  67%|█████████████████████████████████████████████████████████████████████████▎                                   | 5143/7653 [05:15<1:32:12,  2.20s/step, loss=0.557, step=5143]
Traceback (most recent call last):
  File "/home/mads_syv_ai/F5-TTS/finetune-cli.py", line 127, in <module>
    main()
  File "/home/mads_syv_ai/F5-TTS/finetune-cli.py", line 120, in main
    trainer.train(
  File "/home/mads_syv_ai/F5-TTS/model/trainer.py", line 270, in train
    loss, cond, pred = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mads_syv_ai/F5-TTS/model/cfm.py", line 279, in forward
    pred = self.transformer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mads_syv_ai/F5-TTS/model/backbones/dit.py", line 155, in forward
    x = block(x, t, mask=mask, rope=rope)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mads_syv_ai/F5-TTS/model/modules.py", line 486, in forward
    attn_output = self.attn(x=norm, mask=mask, rope=rope)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mads_syv_ai/F5-TTS/model/modules.py", line 312, in forward
    return self.processor(self, x, mask=mask, rope=rope)
  File "/home/mads_syv_ai/F5-TTS/model/modules.py", line 366, in __call__
    x = attn.to_out[1](x)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/dropout.py", line 70, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 1425, in dropout
    _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 338.00 MiB. GPU 0 has a total capacity of 79.14 GiB of which 29.62 MiB is free. Including non-PyTorch memory, this process has 79.10 GiB memory in use. Of the allocated memory 77.51 GiB is allocated by PyTorch, and 1.08 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/home/mads_syv_ai/F5-TTS/finetune-cli.py", line 127, in <module>
    main()
  File "/home/mads_syv_ai/F5-TTS/finetune-cli.py", line 120, in main
    trainer.train(
  File "/home/mads_syv_ai/F5-TTS/model/trainer.py", line 270, in train
    loss, cond, pred = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mads_syv_ai/F5-TTS/model/cfm.py", line 279, in forward
    pred = self.transformer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mads_syv_ai/F5-TTS/model/backbones/dit.py", line 155, in forward
    x = block(x, t, mask=mask, rope=rope)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mads_syv_ai/F5-TTS/model/modules.py", line 486, in forward
    attn_output = self.attn(x=norm, mask=mask, rope=rope)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mads_syv_ai/F5-TTS/model/modules.py", line 312, in forward
    return self.processor(self, x, mask=mask, rope=rope)
  File "/home/mads_syv_ai/F5-TTS/model/modules.py", line 366, in __call__
    x = attn.to_out[1](x)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/dropout.py", line 70, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 1425, in dropout
    _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 338.00 MiB. GPU 0 has a total capacity of 79.14 GiB of which 29.62 MiB is free. Including non-PyTorch memory, this process has 79.10 GiB memory in use. Of the allocated memory 77.51 GiB is allocated by PyTorch, and 1.08 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by kmn1024** [comment]
What I mean to suggest is, suppose we have these examples with these durations
ex1, 100
ex2, 1
ex2, 1
ex2, 1

**Comment by kmn1024** [comment]
Could the following happen? Suppose we have these examples with these frames lengths and durations.
ex1: 100, 2.0
ex2: 50, 1.0
ex3: 10, 0.2
ex4: 100, 2.0

Suppose frames_threshold is 101. Then if I understand correctly, DynamicBatchSchedule would create these batches [ex1], [ex4], [ex2, ex3]. When we actually process the [ex2, ex3] batch, because ex3 duration < 0.3, it will try the next item which is ex4. That means the batch becomes [ex2, ex4] which has a total frame length of 150, exceeding the limit of 101, and may cause CUDA oom?

**Comment by SWivid** [comment]
@kmn1024 Ah yes, that makes sense.
Maybe the best way is to filter out null audio samples or we just remove the contraint <0.3?

**Comment by mhenrichsen** [comment]
Thanks for the feedback so far. I'll try to remove the constraint <0.3 and report back.

**Comment by mhenrichsen** [comment]
@kmn1024 @SWivid I ran it without the constraint and here are the result.
```
Epoch 1/10:  67%|█████████████████████████████████████████████████████████████████████████▏                                   | 5142/7653 [05:10<1:31:33,  2.19s/step, loss=0.558, step=5142]
Traceback (most recent call last):
  File "/home/mads_syv_ai/F5-TTS/finetune-cli.py", line 127, in <module>
    main()
  File "/home/mads_syv_ai/F5-TTS/finetune-cli.py", line 120, in main
    trainer.train(
  File "/home/mads_syv_ai/F5-TTS/model/trainer.py", line 259, in train
    for batch in progress_bar:
  File "/opt/conda/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.10/site-packages/accelerate/data_loader.py", line 561, in __iter__
    next_batch = next(dataloader_iter)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 15.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mads_syv_ai/F5-TTS/model/dataset.py", line 131, in __getitem__
    mel_spec = self.mel_spectrogram(audio)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mads_syv_ai/F5-TTS/model/modules.py", line 64, in forward
    mel = self.mel_stft(inp)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 619, in forward
    specgram = self.spectrogram(waveform)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 110, in forward
    return F.spectrogram(
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/functional/functional.py", line 126, in spectrogram
    spec_f = torch.stft(
  File "/opt/conda/lib/python3.10/site-packages/torch/functional.py", line 702, in stft
    input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 5096, in pad
    return torch._C._nn.pad(input, pad, mode, value)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (512, 512) at dimension 2 of input [1, 1, 96]

Traceback (most recent call last):
  File "/home/mads_syv_ai/F5-TTS/finetune-cli.py", line 127, in <module>
    main()
  File "/home/mads_syv_ai/F5-TTS/finetune-cli.py", line 120, in main
    trainer.train(
  File "/home/mads_syv_ai/F5-TTS/model/trainer.py", line 259, in train
    for batch in progress_bar:
  File "/opt/conda/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.10/site-packages/accelerate/data_loader.py", line 561, in __iter__
    next_batch = next(dataloader_iter)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 15.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/mads_syv_ai/F5-TTS/model/dataset.py", line 131, in __getitem__
    mel_spec = self.mel_spectrogram(audio)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mads_syv_ai/F5-TTS/model/modules.py", line 64, in forward
    mel = self.mel_stft(inp)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 619, in forward
    specgram = self.spectrogram(waveform)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 110, in forward
    return F.spectrogram(
  File "/opt/conda/lib/python3.10/site-packages/torchaudio/functional/functional.py", line 126, in spectrogram
    spec_f = torch.stft(
  File "/opt/conda/lib/python3.10/site-packages/torch/functional.py", line 702, in stft
    input = F.pad(input.view(extended_shape), [pad, pad], pad_mode)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 5096, in pad
    return torch._C._nn.pad(input, pad, mode, value)
RuntimeError: Argument #4: Padding size should be less than the corresponding input dimension, but got: padding (512, 512) at dimension 2 of input [1, 1, 96]
```

Maybe I should reprocess the dataset and filter out audio with a duration less than 0.3 and more than 30?

**Comment by SWivid** [comment]
> Maybe I should reprocess the dataset and filter out audio with a duration less than 0.3

Two possible reasons:
- dataset contains null samples.
- torchaudio just go crazy again, fail to load from audio file (i encountered once)

**Comment by kmn1024** [comment]
This happens when input to torch.stft is too short... it prevents you from computing stft over mostly zero-padding, which would be useless.

+1 to just filtering out samples with duration less than 0.3 and more than 30.

**Comment by mhenrichsen** [comment]
I can confirm that after removing all audio lower than 0.3 and higher than 30 it runs fine. Thanks for the help.

**Comment by wanfnc** [comment]
Hi guys, I have similar ploblems. Can you show some advice? 
I am a Sound Engineer, very poor at computer engineering... 
I tried various batch size ( 500~1000 ), and Epochs ( 50~500 ), it stops suddenly. With balckout of my display.
Here's a log.

Epoch 12/50:   0%|          | 0/65 [00:00<?, ?step/s]
Epoch 12/50:   0%|          | 0/65 [00:00<?, ?step/s, loss=1.02, step=716]
Epoch 12/50:   2%|1         | 1/65 [00:00<00:11,  5.41step/s, loss=1.02, step=716]
Epoch 12/50:   2%|1         | 1/65 [00:00<00:11,  5.41step/s, loss=0.745, step=717]
Epoch 12/50:   3%|3         | 2/65 [00:00<00:10,  6.28step/s, loss=0.745, step=717]
Epoch 12/50:   3%|3         | 2/65 [00:00<00:10,  6.28step/s, loss=1.28, step=718]
Epoch 12/50:   5%|4         | 3/65 [00:00<00:09,  6.63step/s, loss=1.28, step=718]
Epoch 12/50:   5%|4         | 3/65 [00:00<00:09,  6.63step/s, loss=0.712, step=719]
Epoch 12/50:   6%|6         | 4/65 [00:00<00:09,  6.74step/s, loss=0.712, step=719]
Epoch 12/50:   6%|6         | 4/65 [00:00<00:09,  6.74step/s, loss=0.503, step=720]
Epoch 12/50:   8%|7         | 5/65 [00:00<00:08,  6.88step/s, loss=0.503, step=720]
Epoch 12/50:   8%|7         | 5/65 [00:00<00:08,  6.88step/s, loss=0.38, step=721]
Epoch 12/50:   9%|9         | 6/65 [00:00<00:08,  6.75step/s, loss=0.38, step=721]
Epoch 12/50:   9%|9         | 6/65 [00:01<00:08,  6.75step/s, loss=0.466, step=722]
Epoch 12/50:  11%|#         | 7/65 [00:01<00:08,  6.86step/s, loss=0.466, step=722]
Epoch 12/50:  11%|#         | 7/65 [00:01<00:08,  6.86step/s, loss=5.56, step=723]
Epoch 12/50:  12%|#2        | 8/65 [00:01<00:08,  6.90step/s, loss=5.56, step=723]
Epoch 12/50:  12%|#2        | 8/65 [00:01<00:08,  6.90step/s, loss=1.36, step=724]
Epoch 12/50:  14%|#3        | 9/65 [00:01<00:08,  6.92step/s, loss=1.36, step=724]
Epoch 12/50:  14%|#3        | 9/65 [00:01<00:08,  6.92step/s, loss=0.509, step=725]
Epoch 12/50:  15%|#5        | 10/65 [00:01<00:07,  6.96step/s, loss=0.509, step=725]
Epoch 12/50:  15%|#5        | 10/65 [00:01<00:07,  6.96step/s, loss=0.392, step=726]
Epoch 12/50:  17%|#6        | 11/65 [00:01<00:07,  6.99step/s, loss=0.392, step=726]
Epoch 12/50:  17%|#6        | 11/65 [00:01<00:07,  6.99step/s, loss=0.469, step=727]
Epoch 12/50:  18%|#8        | 12/65 [00:01<00:07,  7.00step/s, loss=0.469, step=727]
Epoch 12/50:  18%|#8        | 12/65 [00:01<00:07,  7.00step/s, loss=0.482, step=728]
Epoch 12/50:  20%|##        | 13/65 [00:01<00:07,  7.10step/s, loss=0.482, step=728]
Epoch 12/50:  20%|##        | 13/65 [00:02<00:07,  7.10step/s, loss=0.958, step=729]
Epoch 12/50:  22%|##1       | 14/65 [00:02<00:07,  7.15step/s, loss=0.958, step=729]
Epoch 12/50:  22%|##1       | 14/65 [00:02<00:07,  7.15step/s, loss=0.526, step=730]
Epoch 12/50:  23%|##3       | 15/65 [00:02<00:06,  7.22step/s, loss=0.526, step=730]
Epoch 12/50:  23%|##3       | 15/65 [00:02<00:06,  7.22step/s, loss=0.638, step=731]
Epoch 12/50:  25%|##4       | 16/65 [00:02<00:06,  7.11step/s, loss=0.638, step=731]
Epoch 12/50:  25%|##4       | 16/65 [00:02<00:06,  7.11step/s, loss=0.968, step=732]
Epoch 12/50:  26%|##6       | 17/65 [00:02<00:06,  7.18step/s, loss=0.968, step=732]
Epoch 12/50:  26%|##6       | 17/65 [00:02<00:06,  7.18step/s, loss=2.71, step=733]
Epoch 12/50:  28%|##7       | 18/65 [00:02<00:06,  7.21step/s, loss=2.71, step=733]
Epoch 12/50:  28%|##7       | 18/65 [00:02<00:06,  7.21step/s, loss=0.73, step=734]
Epoch 12/50:  29%|##9       | 19/65 [00:02<00:06,  7.22step/s, loss=0.73, step=734]
Epoch 12/50:  29%|##9       | 19/65 [00:02<00:06,  7.22step/s, loss=0.66, step=735]
Epoch 12/50:  31%|###       | 20/65 [00:02<00:06,  7.24step/s, loss=0.66, step=735]
Epoch 12/50:  31%|###       | 20/65 [00:03<00:06,  7.24step/s, loss=0.84, step=736]
Epoch 12/50:  32%|###2      | 21/65 [00:03<00:06,  7.19step/s, loss=0.84, step=736]
Epoch 12/50:  32%|###2      | 21/65 [00:03<00:06,  7.19step/s, loss=0.443, step=737]
Epoch 12/50:  34%|###3      | 22/65 [00:03<00:05,  7.24step/s, loss=0.443, step=737]
Epoch 12/50:  34%|###3      | 22/65 [00:03<00:05,  7.24step/s, loss=0.655, step=738]
Epoch 12/50:  35%|###5      | 23/65 [00:03<00:05,  7.28step/s, loss=0.655, step=738]
Epoch 12/50:  35%|###5      | 23/65 [00:03<00:05,  7.28step/s, loss=0.551, step=739]
Epoch 12/50:  37%|###6      | 24/65 [00:03<00:05,  7.32step/s, loss=0.551, step=739]
Epoch 12/50:  37%|###6      | 24/65 [00:03<00:05,  7.32step/s, loss=2.87, step=740]
Epoch 12/50:  38%|###8      | 25/65 [00:03<00:05,  7.32step/s, loss=2.87, step=740]
Epoch 12/50:  38%|###8      | 25/65 [00:03<00:05,  7.32step/s, loss=0.413, step=741]
Epoch 12/50:  40%|####      | 26/65 [00:03<00:05,  7.17step/s, loss=0.413, step=741]
Epoch 12/50:  40%|####      | 26/65 [00:14<00:21,  1.83step/s, loss=0.413, step=741]
Traceback (most recent call last):
  File "D:\AI_Projects\f5tts\F5-TTS\src\f5_tts\train\finetune_cli.py", line 161, in <module>
    main()
  File "D:\AI_Projects\f5tts\F5-TTS\src\f5_tts\train\finetune_cli.py", line 154, in main
    trainer.train(
  File "D:\AI_Projects\f5tts\F5-TTS\src\f5_tts\model\trainer.py", line 311, in train
    self.ema_model.update()
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\ema_pytorch\ema_pytorch.py", line 270, in update
    step = self.step.item()
           ^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\accelerate\commands\launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\accelerate\commands\launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\AI_Projects\\f5tts\\F5-TTS\\venv\\Scripts\\python.exe', 'src/f5_tts/train/finetune_cli.py', '--exp_name', 'F5TTS_Base', '--learning_rate', '1e-05', '--batch_size_per_gpu', '500', '--batch_size_type', 'frame', '--max_samples', '64', '--grad_accumulation_steps', '1', '--max_grad_norm', '1', '--epochs', '50', '--num_warmup_updates', '6', '--save_per_updates', '5000', '--last_per_steps', '1000', '--dataset_name', '1212_test02', '--finetune', 'True', '--tokenizer', 'pinyin', '--log_samples', 'True', '--logger', 'tensorboard']' returned non-zero exit status 1.

**Comment by wanfnc** [comment]
I just success the training chainging logger type: wandb ( 50 epochs, 500 batch size ) , but failed while testing model.
Can I get some advice? Should I change specific version of Pytorch or CUDA?
Thanks.

Fetching 4 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\gradio\blocks.py", line 2043, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\gradio\blocks.py", line 1590, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\src\f5_tts\train\finetune_gradio.py", line 1234, in infer
    tts_api = F5TTS(
              ^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\src\f5_tts\api.py", line 51, in __init__
    self.duration_model = load_duration_model()
                          ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\src\f5_tts\infer\utils_infer.py", line 245, in load_duration_model
    transformer=DurationTransformer(
                ^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\src\f5_tts\model\modules.py", line 814, in __init__
    self.input_embed = DurationInputEmbedding(mel_dim, text_dim, dim).to(self.device)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "D:\AI_Projects\f5tts\F5-TTS\venv\Lib\site-packages\torch\nn\modules\module.py", line 1160, in convert
    return t.to(
           ^^^^^
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
