### ISSUE TITLE
gradio shape errors

### ISSUE THREAD

**Issue by lucyknada** [SWivid/F5-TTS#25]
trying any sample audio at all, no matter the format (wav, mp3, ..) I consistently get this error:

```
Traceback (most recent call last):
  File "/workspace/F5-TTS/venv/lib/python3.11/site-packages/gradio/queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/F5-TTS/venv/lib/python3.11/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/F5-TTS/venv/lib/python3.11/site-packages/gradio/blocks.py", line 2016, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/F5-TTS/venv/lib/python3.11/site-packages/gradio/blocks.py", line 1569, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/F5-TTS/venv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/F5-TTS/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/workspace/F5-TTS/venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/F5-TTS/venv/lib/python3.11/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/workspace/F5-TTS/gradio_app.py", line 154, in infer
    generated, _ = base_model.sample(
                   ^^^^^^^^^^^^^^^^^^
  File "/workspace/F5-TTS/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/F5-TTS/model/cfm.py", line 120, in sample
    assert text.shape[0] == batch
           ^^^^^^^^^^^^^^^^^^^^^^
 ```

the same error prevents this space from working: https://huggingface.co/spaces/mrfakename/E2-F5-TTS and from-scratch git pulling this repo and setting it all up crashes it too.

I tried latest gradio and 4.44.1 (in case v5 is breaking everything).

**Comment by SWivid** [comment]
a very possible reason is that you are using multichannel audio

**Comment by lucyknada** [comment]
do you happen to have a file that is guaranteed to work so I can test that? thanks

**Comment by SWivid** [comment]
Any audio with mono channel is fine I thought, e.g. [tests/ref_audio](https://github.com/SWivid/F5-TTS/blob/9395289d7aaafc5add8a53ac4e51675aaa67f9c1/tests/ref_audio/test_en_1_ref_short.wav)

**Comment by matbee-eth** [comment]
Yes thats the issue- I had to convert audio to mono for it to work

**Comment by lucyknada** [comment]
can confirm! that indeed solves the issue, since ffmpeg is a dependency already, could maybe detect and auto convert to mono?

**Comment by SWivid** [comment]
fixed in 83fbd34dc8ad890e9f43d4dd53382af9ac1fa9bb
```
# Audio
audio, sr = torchaudio.load(ref_audio)
if audio.shape[0] > 1:
    audio = torch.mean(audio, dim=0, keepdim=True)
```
And may need @fakerybakery 's help with hf space demo deployment~

**Comment by fakerybakery** [comment]
Thanks! Pushed this to the Space

**Comment by lucyknada** [comment]
space and gradio both work now! thanks!
