### ISSUE TITLE
 Calculated padded input size per channel

### ISSUE THREAD

**Issue by gezeralperen** [SWivid/F5-TTS#255]
While using gradio, I can not synthesize output. I get the error log below.

`gen_text 1 Test text
Traceback (most recent call last):
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\f5_tts\infer\infer_gradio.py", line 90, in infer
    final_wave, final_sample_rate, combined_spectrogram = infer_process(
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\f5_tts\infer\utils_infer.py", line 263, in infer_process
    return infer_batch_process(
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\f5_tts\infer\utils_infer.py", line 343, in infer_batch_process
    generated_wave = vocos.decode(generated_mel_spec.cpu())
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\vocos\pretrained.py", line 112, in decode
    x = self.backbone(features_input, **kwargs)
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\vocos\models.py", line 79, in forward
    x = self.embed(x)
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\torch\nn\modules\conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\alper\.conda\envs\f5-tts\lib\site-packages\torch\nn\modules\conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size`

**Comment by SWivid** [comment]
> `gen_text 1 Test text`

Maybe try with a more reasonable input e.g. Test text for F5-TTS generation, test test.

**Comment by br0ze** [comment]
gen_text 0 Once upon a time, there was a chicken who dreamed of becoming an artist.
Generating audio in 1 batches...
Converting audio...
Using cached reference text...
gen_text 0 It wanted to perform on a big stage, but no one believed a chicken could do that.
Generating audio in 1 batches...
Converting audio...
Using cached reference text...
gen_text 0 However, the chicken didn’t give up.
Generating audio in 1 batches...
Converting audio...
Audio is over 18s, clipping short.
No reference text provided, transcribing reference audio...
Finished transcription
gen_text 0 Once upon a time,
gen_text 1 there was a chicken who dreamed of becoming an artist.
Generating audio in 2 batches...
Traceback (most recent call last):
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 406, in generate_multistyle_speech
    audio, _ = infer(
  File "D:\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 92, in infer
    final_wave, final_sample_rate, combined_spectrogram = infer_process(
  File "D:\F5-TTS\src\f5_tts\infer\utils_infer.py", line 263, in infer_process
    return infer_batch_process(
  File "D:\F5-TTS\src\f5_tts\infer\utils_infer.py", line 343, in infer_batch_process
    generated_wave = vocos.decode(generated_mel_spec.cpu())
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\vocos\pretrained.py", line 112, in decode
    x = self.backbone(features_input, **kwargs)
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\vocos\models.py", line 79, in forward
    x = self.embed(x)
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\torch\nn\modules\conv.py", line 310, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Henry Huynh\miniconda3\envs\f5\lib\site-packages\torch\nn\modules\conv.py", line 306, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size
I got this error too

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions

**Comment by jason-kane** [comment]
Same error, but I'm calling infer_process directly.
```
                        audio, final_sample_rate, spectragram = infer_process(                                                                                                                                     
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/f5_tts/infer/utils_infer.py", line 331, in infer_process                                                                          
                        return infer_batch_process(                                                                                                                                                                
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/f5_tts/infer/utils_infer.py", line 416, in infer_batch_process                                                                    
                        generated_wave = vocoder.decode(generated_mel_spec)                                                                                                                                        
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context                                                                        
                        return func(*args, **kwargs)                                                                                                                                                               
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/vocos/pretrained.py", line 112, in decode                                                                                         
                        x = self.backbone(features_input, **kwargs)                                                                                                                                                
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl                                                                     
                        return self._call_impl(*args, **kwargs)                                                                                                                                                    
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl                                                                             
                        return forward_call(*args, **kwargs)                                                                                                                                                       
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/vocos/models.py", line 79, in forward                                                                                             
                        x = self.embed(x)                                                                                                                                                                          
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl                                                                     
                        return self._call_impl(*args, **kwargs)                                                                                                                                                    
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl                                                                             
                        return forward_call(*args, **kwargs)                                                                                                                                                       
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 308, in forward                                                                                   
                        return self._conv_forward(input, self.weight, self.bias)                                                                                                                                   
                      File "/home/jkane/books/.venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 304, in _conv_forward                                                                             
                        return F.conv1d(input, weight, bias, self.stride,                                                                                                                                          
                    RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size
```

**Comment by SWivid** [comment]
@jason-kane how is the input output and used command
