### ISSUE TITLE
how to f5 tts train for other language

### ISSUE THREAD

**Issue by Chiyan200** [SWivid/F5-TTS#291]
I have over 200 hours of voice data in the Tamil language, and I'm interested in training my own custom language model using F5 TTS. Could you guide me on the steps required to prepare and train the model effectively with this dataset? Specifically, I’d like advice on data preprocessing, setting up the model configuration, and any additional considerations for achieving accurate and grammatically correct Tamil output.

**Comment by lpscr** [comment]
hi @Chiyan200 here a gradio finetune i working on step by step easy  , for new language **check vocab** to see if miss any symbols ! if you miss any symbols let me know if not you can finetune fine , 
also change the per step = 20000 and last step 5000 epochs about =30 be ok you can stop manual

https://github.com/SWivid/F5-TTS/discussions/143

**Comment by Chiyan200** [comment]
![error](https://github.com/user-attachments/assets/1585cb02-de97-498c-af99-3841c3423f8b)
This 


> hi @Chiyan200 here a gradio finetune i working on step by step easy , for new language **check vocab** to see if miss any symbols ! if you miss any symbols let me know , if not miss anyting you can finetune fine , also change the per step = 20000 and last step 5000 epochs about =30 be ok you can stop manual around 100 -150 k you must have a good results check model to see in **test model tab**
> 
> #143
![error](https://github.com/user-attachments/assets/623da64c-00ea-4af9-9570-ad7dbfabaaaf)
i put sample audio file to test this process . but i got an error while run a start training this my Error
![error1](https://github.com/user-attachments/assets/2659878b-4eaa-4677-9091-c02d7d0399de)
but i have all file 
![folder path](https://github.com/user-attachments/assets/1f571fcd-e055-4e11-81ce-5d0ad075c5bd)
can resolve this issue
vocab missing how i can fix this 
![vocab missing](https://github.com/user-attachments/assets/a35b4c13-4680-4900-9400-9953d3dea2ef)

**Comment by lpscr** [comment]
@Chiyan200 what format you use in metadata.csv 
audio_name|text ?

**Comment by lpscr** [comment]
@Chiyan200 i working new update now you can train any langauge ! 
i just new update 
![image](https://github.com/user-attachments/assets/54c0ff4e-2949-4edc-9034-4dc4c18d4be8)

**Comment by Chiyan200** [comment]
This meatadata.csv
segment_0|தனிமணித தவருகளை விட
segment_1|ஒரு கும்பலின் தவரு அதிகப்படியான பாதிப்பு உண்டாக்கும்
segment_2|இப்போது பல சொந்தம் என்னை பிரிந்து செல்ல தொடங்கி விட்டது
segment_3|இனி பண்டிகை நாட்களில்
segment_4|மொக்கப் படங்கள் மட்டும் தான் வெளிவரும் மாம்

This my folder structure
![folder](https://github.com/user-attachments/assets/89c4220f-ac33-4e01-92a4-23a46c9aa347)

**Comment by Chiyan200** [comment]
Same issues 
![newIssue](https://github.com/user-attachments/assets/6dfbc62f-09ef-4a55-b096-9983d8029cf7)

here is new vocab
![vocabNew](https://github.com/user-attachments/assets/ad81150c-ddc9-4bbe-b836-c2cde26b8b52)

**Comment by lpscr** [comment]
@i think the problem it's you run from wrong path
make sure you are in path where it's the repo

`C:\PythonApps\ff5ttsmy\F5-TTS`
then run 
`python .\src\f5_tts\train\finetune_gradio.py`

**Comment by lpscr** [comment]
@Chiyan200 i see one min test it right now

**Comment by Chiyan200** [comment]
> @Chiyan200 i see one min test it right now

I don't understand what you mean

**Comment by lpscr** [comment]
@Chiyan200 hi, i just made new update fix stuff , check it when the main repo update also , or check in my repo

**Comment by zgongc** [comment]
@Chiyan200 How do you run finetune-cli or finetune-gradio?

If I run it like this **python src/f5_tts/train/finetune_gradio.py**
it looks for the file metadata.csv in the right place.
the file /opt/celal/F5-TTS/data/my_speak_pinyin/metadata.csv not found !

If I run it like this **f5-tts_finetune-gradio**
it looks for the file metadata.csv in another place.
the file /home/celal/miniconda3/envs/f5-tts/lib/python3.10/data/my_speak_pinyin/metadata.csv not found !

@lpscr for your information

**Comment by lpscr** [comment]
@zgongc check new update this working for you ? check my repo or wait upate in main

**Comment by SWivid** [comment]
> @Chiyan200 How do you run finetune-cli or finetune-gradio?
> 
> If I run it like this **python src/f5_tts/train/finetune_gradio.py** it looks for the file metadata.csv in the right place. the file /opt/celal/F5-TTS/data/my_speak_pinyin/metadata.csv not found !
> 
> If I run it like this **f5-tts_finetune-gradio** it looks for the file metadata.csv in another place. the file /home/celal/miniconda3/envs/f5-tts/lib/python3.10/data/my_speak_pinyin/metadata.csv not found !
> 
> @lpscr for your information

have you do `pip install -e .`?

**Comment by zgongc** [comment]
> > @Chiyan200 How do you run finetune-cli or finetune-gradio?
> > If I run it like this **python src/f5_tts/train/finetune_gradio.py** it looks for the file metadata.csv in the right place. the file /opt/celal/F5-TTS/data/my_speak_pinyin/metadata.csv not found !
> > If I run it like this **f5-tts_finetune-gradio** it looks for the file metadata.csv in another place. the file /home/celal/miniconda3/envs/f5-tts/lib/python3.10/data/my_speak_pinyin/metadata.csv not found !
> > @lpscr for your information
> 
> have you do `pip install -e .`?

I think that's the problem. I installed it as written, but it was not up to date and there were errors. I reinstalled it now and it finds the files as it should.

**Comment by Chiyan200** [comment]
> @zgongc @Chiyan200 check new update this working for you ? check my repo or wait upate in main

I checked same issue happens 
this given command  to run trian gradio i   D:/software/miniconda3/envs/f5-tts/python.exe
 f:/F5-TTS/src/f5_tts/train/finetune_gradio.py

![same Err](https://github.com/user-attachments/assets/a1cb4ca8-4937-4457-ab65-1e0408485441)

also i run f5-tts_finetune-gradio It this Error so tried above the command 
![gradio Err](https://github.com/user-attachments/assets/61142896-0d65-4c51-80dc-f9b45d973477)

**Comment by Chiyan200** [comment]
> > @Chiyan200 How do you run finetune-cli or finetune-gradio?
> > 
> > If I run it like this **python src/f5_tts/train/finetune_gradio.py** it looks for the file metadata.csv in the right place. the file /opt/celal/F5-TTS/data/my_speak_pinyin/metadata.csv not found !
> > 
> > If I run it like this **f5-tts_finetune-gradio** it looks for the file metadata.csv in another place. the file /home/celal/miniconda3/envs/f5-tts/lib/python3.10/data/my_speak_pinyin/metadata.csv not found !
> > 
> > @lpscr for your information
> 
> have you do `pip install -e .`?

No,
I am using conda 
I used this command pip install git+https://github.com/SWivid/F5-TTS.git 

I checked same issue happens 
this given command  to run trian gradio i   D:/software/miniconda3/envs/f5-tts/python.exe
 f:/F5-TTS/src/f5_tts/train/finetune_gradio.py

![same Err](https://github.com/user-attachments/assets/a1cb4ca8-4937-4457-ab65-1e0408485441)

also i run f5-tts_finetune-gradio It this Error so tried above the command 
![gradio Err](https://github.com/user-attachments/assets/61142896-0d65-4c51-80dc-f9b45d973477)

**Comment by SWivid** [comment]
> No,
> I am using conda
> I used this command pip install git+https://github.com/SWivid/F5-TTS.git

That is just the source of issue you faced.
If you want to do training, do `pip install -e .` rather than `pip install git+https://github.com/SWivid/F5-TTS.git`

In readme, we put it like `pip install git+https://github.com/SWivid/F5-TTS.git` **(if inference-only)**

**Comment by attashe** [comment]
@SWivid 
Is this lines with missed indent?
https://github.com/SWivid/F5-TTS/blob/5d8180ea58060dc022cc8ef85f4c9afb5dbf5a2b/src/f5_tts/model/dataset.py#L186C1-L187C34
And should be:
```python
        batch = []
        batch_frames = 0
        for idx, frame_len in tqdm(
            indices, desc=f"Creating dynamic batches with {frames_threshold} audio frames per gpu"
        ):
            if batch_frames + frame_len <= self.frames_threshold and (max_samples == 0 or len(batch) < max_samples):
                batch.append(idx)
                batch_frames += frame_len
            else:
                if len(batch) > 0:
                    batches.append(batch)
                if frame_len <= self.frames_threshold:
                    batch = [idx]
                    batch_frames = frame_len
                else:
                    batch = []
                    batch_frames = 0

            if not drop_last and len(batch) > 0:
                batches.append(batch)
```

**Comment by Chiyan200** [comment]
@SWivid  @lpscr 
Finally, the training is running successfully! I have one question: Can I continue my training? eg if trained 10 epochs then after i train 20 epochs like ?

My graphics card is an RTX 2060 Super 8GB, and I have over 200 hours of training data. What would be the best settings and the correct number of epochs for this setup?

![taininng](https://github.com/user-attachments/assets/9d9d833a-8c18-419c-bd23-93a05fe3e4dd)

**Comment by abhisirka2001** [comment]
> @SWivid @lpscr Finally, the training is running successfully! I have one question: Can I continue my training? eg if trained 10 epochs then after i train 20 epochs like ?
> 
> My graphics card is an RTX 2060 Super 8GB, and I have over 200 hours of training data. What would be the best settings and the correct number of epochs for this setup?
> 
> ![taininng](https://private-user-images.githubusercontent.com/94426967/380832725-9d9d833a-8c18-419c-bd23-93a05fe3e4dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTMzOTQsIm5iZiI6MTczMDE1MzA5NCwicGF0aCI6Ii85NDQyNjk2Ny8zODA4MzI3MjUtOWQ5ZDgzM2EtOGMxOC00MTljLWJkMjMtOTNhMDVmZTNlNGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDIyMDQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhNDEwNzRlMWNiNzU0ZGUzMDZmZTRmYWQzMmViZDFjNjI4OWNjNDQ2NTkzNzFjNTUzNGEyMjNmOTIxNzhkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AFoCkvApbGwz_QPXGRkfEMFg7SAL6R-Ae-IqU5hvJA8)

Hey 

I have been trying to finetune my F5 model for Gujarati language
Can you please help me prepare the vocab file for it?
like what exactly did you use for preparing the indic vocab.txt
the current one in the repo doesnt work for indian language.
I had a trial on brazilian portuguese data and it was working as i could use the same vocab.

Thanks

**Comment by sachin-seisei** [comment]
@abhisirka2001 u meant create_metadata(name_project, ch_tokenizer=True, progress=gr.Progress()) method did not help for generating vocab.txt file??

**Comment by zgongc** [comment]
Hello @lpscr,
Here is a log of my experiments.

`python src/f5_tts/train/finetune_gradio.py --host 0.0.0.0`


create new project --> my_speak

**1. transcribe Data**

check audio from path 
copy sample wavs file to dataset
change Language english to turkish

> transcribe complete samples : 116
> path : D:\github\F5-TTS\src\f5_tts\..\..\data\my_speak_pinyin\wavs
> error files : 0

**2. vocab check**

check vocab

> The following symbols are missing in your language 1

click Extended


> vocab old size : 2546
> vocab new size : 2547
> vocab add : 1
> new symbols :

check vocab again
> The following symbols are missing in your language 1


load extended vocab.txt file and use this for project


now have 
metadata.cvs
vocab.txt
wavs folder


**3. prepare Data**

click prepare

> prepare complete 
> samples : 116
> time data : 00:05:48
> min sec : 0.3
> max sec : 4.62
> file_arrow : D:\github\F5-TTS\src\f5_tts\..\..\data\my_speak_pinyin\raw.arrow
> vocab : 2546


your metadata.cvs file format is
audio1|text1

please use mp3 file extensions to and write the entire file name in metadata.cvs. (if not have wav file more advantage)
audio1.mp3|text1

transcribe does not write the descriptions exactly, at least for turkish.
It would be better if we use our own metadata.cvs file.


**4. train Data**

click Auto Settings

make epochs 10 than Start Training

done

error note:

> if mixed_precision --> fpb16 selected
> accelerate <command> [<args>] launch: error: argument --mixed_precision/--mixed-precision: invalid choice: 'fpb16' (choose from 'no', 'fp16', 'bf16', 'fp8')


**5. test model**

select checkpoints

random sample than infer

the result is the same as model_1200000.pt



If we want to use the texts in the trained audio file, how long do I need to train the audio file?
Because I don't have enough space for 70890 epochs.

Is there anything I did wrong or missing?

**Comment by lpscr** [comment]
@zgongc the fp16 not suport in your gpu card i think that's you get this error
also about from new langauge you need at less 15 - 20 hours like i see other success to finetune complete new langauge for single speak
another think it's change the `save per step` so dont save a lot check point see the sample you have and try find something good
in about 20k-40k check see how it's the model in this step you must start get something good like i see 
also check here for more info stuff https://github.com/SWivid/F5-TTS/discussions/57

**Comment by zgongc** [comment]
@lpscr
>  the fp16 not suport in your gpu card i think that's you get this error 

but you are sending  **'fpb16'** , there is no choice option in accelerate
>--mixed-precision: invalid choice: 'fpb16' (choose from 'no', 'fp16', 'bf16', 'fp8')

**Comment by inconnu26** [comment]
I am very interested in having the model trained for other languages. Especially French language. Can a kind soul share a step by step tutorial to achieve this? Thank you!

**Comment by lpscr** [comment]
@inconnu26 hi try use finetune gradio its step by step

https://github.com/SWivid/F5-TTS/discussions/143

you have dataset with a lot of hours then you can use to finetune see help

**Comment by sachin7695** [comment]
@lpscr can you explain in detail about the tokenization part?? Like say that I have a Metadata.csv file structure being chunk_001.wav|"text string" and I want to generate the vocab.txt file from scratch for a new set of language how can I proceed?? Need a clear explanation!! Thanks

**Comment by zgongc** [comment]
@lpscr I finally was able to teach the model something
but I had to create a new enviroment for this. (python=3.10 and cuda118 didn't work for me)

```
conda create -n tts python=3.12
conda activate tts

# https://pytorch.org/get-started/locally/
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

in f5-tts folder
pip install -e .
```

Your latest changes are pretty good.
It would be great if there was something in **prepare data**
`very small text len ​​3 and duration < 1 or > 25 `
where the user can specify the size. 
Some words like "up", "one", "two" or "A", "B" are under < 3

Like this;
```
if duration < user_duration_len_min or duration > user_duration_len_max: 
   error_files.append([file_audio, "duration < 1 or > 25 "]) 
   continue 
if len(text) < user_text_len: 
   error_files.append([file_audio, "very small text len ​​3"]) 
   continue
```

**Comment by liuhui881125** [comment]
未来有兼容其他小语种的计划么？或者能不能提供一些训练小语种的方案？ @SWivid

**Comment by SWivid** [comment]
@liuhui881125 readme指向的discussion board已经有不少人成功在各种语言上微调成功，可以参考他们的经验
同时在这些地方我们也都表明了是有朝更多语言支持方向发展的计划

**Comment by i-am-flashh** [comment]
@Chiyan200 Have you trained model for tamil language? How was the output?

**Comment by zakmez** [comment]
Will a higher sample rate and bit depth in the audio dataset improve the quality of training results?

**Comment by Chiyan200** [comment]
> @Chiyan200 Have you trained model for tamil language? How was the output?
> 

No

**Comment by Chiyan200** [comment]
> @sachin7695 Hi! You can use the vocab.txt file, which already supports a lot of characters.  go to the vocab check to see what's missing and then extend the vocabulary. This way, you can fine-tune the model with fewer hours for the dataset. 
> It seems to be working great, as others have mentioned here as well.
> 
> You only need the metadata.csv file and a folder with audio files in the wav format, 
> 
> with format 
> 
> audio1|text1
> audio2|text3
> ...
> 
> Next, go to the prepare tab and create the dataset with tokens. You can also see how your text tokens and audio look. Click on "random sample" to check how your tokens and audio appear. If everything looks good, you can start training.
> 
> If you want a completely new vocabulary, you'll need to train from scratch, which will take several days and require a huge dataset of about 1k hours. For more advanced information, check out this discussion: https://github.com/SWivid/F5-TTS/discussions/57 
> 
> see also here  
> https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/train
> 
> 
> 
> 
> 

Hey , I tried on my local mission but it takes a lot of time so I decided to move to the cloud. I have some doubts in the train for 60 hours of data in tamil language . how many epoch is the best for getting a minimum result .

I want this data for calculation purposes. How many hours does it take?

**Comment by Chiyan200** [comment]
> hi @Chiyan200 here a gradio finetune i working on step by step easy  , for new language **check vocab** to see if miss any symbols ! if you miss any symbols let me know , if not miss anyting you can finetune fine , 
> also change the per step = 20000 and last step 5000 epochs about =30 be ok you can stop manual around 100 -150 k you must have a good results check model to see in **test model tab**
> 
> https://github.com/SWivid/F5-TTS/discussions/143
> 
> 
> 
@lpscr 
Hey , I tried on my local mission but it takes a lot of time so I decided to move to the cloud. I have some doubts in the train for 60 hours of data in tamil language . how many epoch is the best for getting a minimum result .

I want this data for calculation purposes. How many hours does it take?

**Comment by vicecity-sys** [comment]
Bro, @Chiyan200 , can you share the dataset link? I have a 4090 and want to try.

**Comment by Chiyan200** [comment]
> Bro, @Chiyan200 , can you share the dataset link? I have a 4090 and want to try.
> 
 Sorry man this is my private data :)

**Comment by Anas-KhanWP** [comment]
Hey, @lpscr 
I am trying to train it for multilingual (more specifically for Arabic and Urdu) But unfortunately, I am unable to pass the transcribe barrier for multilingual dataset. Could you please help me out with it?

Like what should I Put in Language input for it to detect the language automatically? I have already tried the following:
Arabic, Urdu
Auto
Arabic | Urdu

And If there is no way to do so, Could you please guide me through the manual process of it?

Thanks.

**Comment by Chiyan200** [comment]
> Hey, @lpscr 
> I am trying to train it for multilingual (more specifically for Arabic and Urdu) But unfortunately, I am unable to pass the transcribe barrier for multilingual dataset. Could you please help me out with it?
> 
> Like what should I Put in Language input for it to detect the language automatically? I have already tried the following:
> Arabic, Urdu
> Auto
> Arabic | Urdu
> 
> And If there is no way to do so, Could you please guide me through the manual process of it?
> 
> Thanks.
> 
@Anas-KhanWP 
You'll create a  separate folder for Arabic and Urdu voices then transcribe . After transcribing you can move in a single folder it will .
 If there are any doubts watch this video https://youtu.be/GmketyZW2c4?feature=shared

**Comment by Anas-KhanWP** [comment]
Thanks @Chiyan200 

I was also thinking the same and did the same thing. I merged the metadata.csv after renaming the the files as per the sequence, what I was thinking was the vocab.txt file, How would I Merge it?

Also, If I already have a pretrained model, I want to finetune it more (include another language on top of it or to finetune it more on the already trained languages) what Should I Put in these tabs?

I assume that pretrained checkpoint path would look something like this: "E:\CloneV\F5-TTS\ckpts\my_speak_test_transcribe\model_1200000.pt" but what should I Put in Tokenizer File?

![image](https://github.com/user-attachments/assets/90dc4348-62c4-4dcb-b728-69b6eb033ea3)

**Comment by attashe** [comment]
Trained a ru model on the ruslan dataset. Doesn't copy reference voice because lack of voice diversity in dataset, 900k training steps

Examples:
[example_1](https://vocaroo.com/1lmH5fpjPPP8)
[example_2](https://vocaroo.com/14cZASssD9Tj)

**Comment by Chiyan200** [comment]
> Trained a ru model on the ruslan dataset. Doesn't copy reference voice because lack of voice diversity in dataset, 900k training steps
> 
> Examples:
> [example_1](https://vocaroo.com/1lmH5fpjPPP8)
> [example_2](https://vocaroo.com/14cZASssD9Tj)

@attashe 
How many hours of data did you used

**Comment by sam4muzix** [comment]
> @SWivid  @lpscr 
> 
> Finally, the training is running successfully! I have one question: Can I continue my training? eg if trained 10 epochs then after i train 20 epochs like ?
> 
> 
> 
> My graphics card is an RTX 2060 Super 8GB, and I have over 200 hours of training data. What would be the best settings and the correct number of epochs for this setup?
> 
> 
> 
> ![taininng](https://github.com/user-attachments/assets/9d9d833a-8c18-419c-bd23-93a05fe3e4dd)
> 
>  

Hi , im hung up with same kind of issues u faces. Please help on how u passed the issue.
Here is my issue

(venv) D:\AI_Programs\PROJECTS\F5\F5-TTS>accelerate launch src/f5_tts/train/train.py
Traceback (most recent call last):
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\src\f5_tts\train\train.py", line 104, in <module>
    main()
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\src\f5_tts\train\train.py", line 56, in main
    tokenizer_path = tokenizer_path
                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'tokenizer_path' where it is not associated with a value
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\venv\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\venv\Lib\site-packages\accelerate\commands\launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\venv\Lib\site-packages\accelerate\commands\launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\AI_Programs\\PROJECTS\\F5\\F5-TTS\\venv\\Scripts\\python.exe', 'src/f5_tts/train/train.py']' returned non-zero exit status 1.

**Comment by attashe** [comment]
> > Trained a ru model on the ruslan dataset. Doesn't copy reference voice because lack of voice diversity in dataset, 900k training steps
> > Examples:
> > [example_1](https://vocaroo.com/1lmH5fpjPPP8)
> > [example_2](https://vocaroo.com/14cZASssD9Tj)
> 
> @attashe How many hours of data did you used

22k short samples -> 31 hours. For inference I use short batches (~200-250 characters with ref) because during finetuning model seen only short examples. Now I training with BigVGAN and it seems to converge faster (~100-200k steps)
https://paperswithcode.com/dataset/ruslan

**Comment by Chiyan200** [comment]
> > > Trained a ru model on the ruslan dataset. Doesn't copy reference voice because lack of voice diversity in dataset, 900k training steps
> > > Examples:
> > > [example_1](https://vocaroo.com/1lmH5fpjPPP8)
> > > [example_2](https://vocaroo.com/14cZASssD9Tj)
> > 
> > 
> > @attashe How many hours of data did you used
> 
> 22k short samples -> 31 hours. For inference I use short batches (~200-250 characters with ref) because during finetuning model seen only short examples. Now I training with BigVGAN and it seems to converge faster (~100-200k steps) https://paperswithcode.com/dataset/ruslan

@attashe 

Does your model clone others' voices perfectly, or not?

**Comment by sam4muzix** [comment]
> which checkout (commit) you are using, seems not the latest version
> 
> you could pull the lastest repo with updated config setup way, using hydra config yaml
> 
> 
> 
> see the latest readme in under train/ directory, and the config yaml files are under configs/

Sure thanks

**Comment by attashe** [comment]
> > > > Trained a ru model on the ruslan dataset. Doesn't copy reference voice because lack of voice diversity in dataset, 900k training steps
> > > > Examples:
> > > > [example_1](https://vocaroo.com/1lmH5fpjPPP8)
> > > > [example_2](https://vocaroo.com/14cZASssD9Tj)
> > > 
> > > 
> > > @attashe How many hours of data did you used
> > 
> > 
> > 22k short samples -> 31 hours. For inference I use short batches (~200-250 characters with ref) because during finetuning model seen only short examples. Now I training with BigVGAN and it seems to converge faster (~100-200k steps) https://paperswithcode.com/dataset/ruslan
> 
> @attashe
> 
> Does your model clone others' voices perfectly, or not?

No, cloning capability of model trained on ruslan dataset is bad. But when I extended dataset from sova (ru films_25h subset) with new voices - cloning became much better

Reference - https://voca.ro/1boUiUqgzHyg
Generation - https://vocaroo.com/12SomCGlT9r7

**Comment by Mudassirkhan2023** [comment]
> Hey, [@lpscr](https://github.com/lpscr) I am trying to train it for multilingual (more specifically for Arabic and Urdu) But unfortunately, I am unable to pass the transcribe barrier for multilingual dataset. Could you please help me out with it?
> 
> Like what should I Put in Language input for it to detect the language automatically? I have already tried the following: Arabic, Urdu Auto Arabic | Urdu
> 
> And If there is no way to do so, Could you please guide me through the manual process of it?
> 
> Thanks.

Hi, Can you help me to train in Urdu language (tokenazier type --Pinyin or Char ?) and trainning from scratch will or should i use pretrained (English and Chinese pretrained)-- I have trainned using Pinyin tokenizer type 25 hrs of Urdu data with 6.8 Lakh steps but it does not speek properly.  I am having 1000 hrs of data for further trainning.

**Comment by oksurya** [comment]
> I have over 200 hours of voice data in the Tamil language, and I'm interested in training my own custom language model using F5 TTS. Could you guide me on the steps required to prepare and train the model effectively with this dataset? Specifically, I’d like advice on data preprocessing, setting up the model configuration, and any additional considerations for achieving accurate and grammatically correct Tamil output.

bro tamil la panitingala ?

**Comment by prasannab4362** [comment]
Hi everyone,

I want to train a Tamil voice cloning TTS model using the F5 framework (or any other suitable solution). I have around 30 minutes of audio data available for training. However, I’m not sure how to proceed with the training process, preprocessing, or setting up the model.

If anyone has experience with Tamil voice cloning or has trained TTS models for Tamil or other languages, please guide me. Also, I’m open to suggestions on frameworks, datasets, or best practices for voice cloning in different languages.

Any help would be greatly appreciated! Thank you.
