### ISSUE TITLE
error message "ffmpeg" [fixed]

### ISSUE THREAD

**Issue by ProxiEx3** [SWivid/F5-TTS#297]
Traceback (most recent call last):
  File "P:\AI\Python\lib\site-packages\transformers\pipelines\audio_utils.py", line 34, in ffmpeg_read
    with subprocess.Popen(ffmpeg_command, stdin=subprocess.PIPE, stdout=subprocess.PIPE) as ffmpeg_process:
  File "P:\AI\Python\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "P:\AI\Python\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] System could not find required file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "P:\AI\Python\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "P:\AI\Python\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "P:\AI\Python\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "P:\AI\Python\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "P:\AI\Python\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "P:\AI\Python\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "P:\AI\Python\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "P:\AI\Python\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "P:\AI\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 85, in infer
    ref_audio, ref_text = preprocess_ref_audio_text(ref_audio_orig, ref_text, show_info=show_info)
  File "P:\AI\F5-TTS\src\f5_tts\infer\utils_infer.py", line 213, in preprocess_ref_audio_text
    ref_text = asr_pipe(
  File "P:\AI\Python\lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 283, in __call__
    return super().__call__(inputs, **kwargs)
  File "P:\AI\Python\lib\site-packages\transformers\pipelines\base.py", line 1294, in __call__
    return next(
  File "P:\AI\Python\lib\site-packages\transformers\pipelines\pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "P:\AI\Python\lib\site-packages\transformers\pipelines\pt_utils.py", line 269, in __next__
    processed = self.infer(next(self.iterator), **self.params)
  File "P:\AI\Python\lib\site-packages\torch\utils\data\dataloader.py", line 701, in __next__
    data = self._next_data()
  File "P:\AI\Python\lib\site-packages\torch\utils\data\dataloader.py", line 757, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "P:\AI\Python\lib\site-packages\torch\utils\data\_utils\fetch.py", line 33, in fetch
    data.append(next(self.dataset_iter))
  File "P:\AI\Python\lib\site-packages\transformers\pipelines\pt_utils.py", line 186, in __next__
    processed = next(self.subiterator)
  File "P:\AI\Python\lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 364, in preprocess
    inputs = ffmpeg_read(inputs, self.feature_extractor.sampling_rate)
  File "P:\AI\Python\lib\site-packages\transformers\pipelines\audio_utils.py", line 37, in ffmpeg_read
    raise ValueError("ffmpeg was not found but is required to load audio files from filename") from error
ValueError: ffmpeg was not found but is required to load audio files from filename

[I get this message when clicking the "Synthesize" button in the web ui. Can anyone help me on what I have to do to fix it?]

**Comment by lpscr** [comment]
@ProxiEx3 check this https://github.com/SWivid/F5-TTS/discussions/143#discussioncomment-11005630

**Comment by ProxiEx3** [comment]
Thank you I never heard of ffmpeg and I must've overlooked it in the f5-tts install instructions! But this worked.

1. Download the "ffmpeg essentials zip" 
2. extract the 3 .exe files into any folder 
3. then create a path under "edit system environment variables" for it 

Done.. Worked for me!

**Comment by SWivid** [comment]
Will close as solved. Feel free to open if further questions.

**Comment by TeacherBobK** [comment]
Where is "edit system environment variables".  I have the files and I did the cmd line text but that didnt work - this, you say, does, but I have no idea where this edit file is.  Can you please direct me to the right place.

**Comment by SWivid** [comment]
try searching for online tutorial of ffmpeg installation on windows, will have guidance how to add ffmpeg to system PATH
