### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for CFM 

### ISSUE THREAD

**Issue by Chiyan200** [SWivid/F5-TTS#307]
Download Vocos from huggingface charactr/vocos-mel-24khz

vocab :  F:\F5-TTS\src\f5_tts\infer\examples\vocab.txt
tokenizer :  custom
model :  F:\F5-TTS\src\f5_tts\..\..\ckpts\my_speak\model_10.pt 

Traceback (most recent call last):
  File "D:\software\miniconda3\envs\f5-tts\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\software\miniconda3\envs\f5-tts\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\software\miniconda3\envs\f5-tts\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "D:\software\miniconda3\envs\f5-tts\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\software\miniconda3\envs\f5-tts\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\software\miniconda3\envs\f5-tts\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "D:\software\miniconda3\envs\f5-tts\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "D:\software\miniconda3\envs\f5-tts\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "F:\F5-TTS\src\f5_tts\train\finetune_gradio.py", line 1185, in infer
    tts_api = F5TTS(model_type=exp_name, ckpt_file=file_checkpoint, device=device_test, use_ema=use_ema)
  File "F:\F5-TTS\src\f5_tts\api.py", line 47, in __init__
    self.load_ema_model(model_type, ckpt_file, vocab_file, ode_method, use_ema)
  File "F:\F5-TTS\src\f5_tts\api.py", line 66, in load_ema_model
    self.ema_model = load_model(model_cls, model_cfg, ckpt_file, vocab_file, ode_method, use_ema, self.device)
  File "F:\F5-TTS\src\f5_tts\infer\utils_infer.py", line 172, in load_model
    model = load_checkpoint(model, ckpt_path, device, use_ema=use_ema)
  File "F:\F5-TTS\src\f5_tts\infer\utils_infer.py", line 137, in load_checkpoint
    model.load_state_dict(checkpoint["model_state_dict"])
  File "D:\software\miniconda3\envs\f5-tts\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CFM:
        size mismatch for transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2574, 512]) from checkpoint, the shape in current model is torch.Size([2546, 512]).

![test model Err ui](https://github.com/user-attachments/assets/7f3833b1-0d1f-400b-93e3-619a1ebbe4bc)

![test model Err](https://github.com/user-attachments/assets/461fe5cb-8873-4ef9-9c0a-ac9ba3f59c19)

**Comment by lpscr** [comment]
@Chiyan200 hi i just fix this problem you can see in main repo when update or in my repo , let me know if this now working for you https://github.com/lpscr/F5-TTS

**Comment by ZhikangNiu** [comment]
You need to check if your vocab is the same as the vocab provided by this repo

**Comment by liuhui881125** [comment]
https://github.com/SWivid/F5-TTS/issues/261

**Comment by ZhikangNiu** [comment]
I will close this issue and you can re-open this issue if you have other questions

**Comment by atlonxp** [comment]
@lpscr I have the same problem. I'm training for a new language, which vocab.txt is extended from the corresponding vocab. any suggestion here?
