### ISSUE TITLE
RuntimeError: cuFFT doesn't support signals of half type with compute capability less than SM_53 setup with pinokio 

### ISSUE THREAD

**Issue by TeriosKrim** [SWivid/F5-TTS#310]
Traceback (most recent call last):
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\gradio\queueing.py", line 536, in proces
s_events
    response = await route_utils.call_process_api(
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\gradio\route_utils.py", line 322, in cal
l_process_api
    output = await app.get_blocks().process_api(
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\gradio\blocks.py", line 1935, in process
_api
    result = await self.call_function(
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\gradio\blocks.py", line 1520, in call_fu
nction
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\anyio\to_thread.py", line 56, in run_syn
c
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 2441,
 in run_sync_in_worker_thread
    return await future
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\anyio\_backends\_asyncio.py", line 943, 
in run
    result = context.run(func, *args)
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\gradio\utils.py", line 826, in wrapper  
    response = f(*args, **kwargs)
  File "C:\pinokio\api\e2-f5-tts.git\app\src\f5_tts\infer\infer_gradio.py", line 92, in infer
    final_wave, final_sample_rate, combined_spectrogram = infer_process(
  File "C:\pinokio\api\e2-f5-tts.git\app\src\f5_tts\infer\utils_infer.py", line 263, in infer_process  
    return infer_batch_process(
  File "C:\pinokio\api\e2-f5-tts.git\app\src\f5_tts\infer\utils_infer.py", line 331, in infer_batch_pro
cess
    generated, _ = model_obj.sample(
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torch\utils\_contextlib.py", line 116, i
n decorate_context
    return func(*args, **kwargs)
  File "C:\pinokio\api\e2-f5-tts.git\app\src\f5_tts\model\cfm.py", line 108, in sample
    cond = self.mel_spec(cond)
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1553, 
in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1562, 
in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\pinokio\api\e2-f5-tts.git\app\src\f5_tts\model\modules.py", line 64, in forward
    mel = self.mel_stft(inp)
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1553, 
in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1562, 
in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torchaudio\transforms\_transforms.py", l
ine 619, in forward
    specgram = self.spectrogram(waveform)
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1553, 
in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torch\nn\modules\module.py", line 1562, 
in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torchaudio\transforms\_transforms.py", l
ine 110, in forward
    return F.spectrogram(
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torchaudio\functional\functional.py", li
ne 126, in spectrogram
    spec_f = torch.stft(
  File "C:\pinokio\api\e2-f5-tts.git\app\env\lib\site-packages\torch\functional.py", line 666, in stft 
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]        
RuntimeError: cuFFT doesn't support signals of half type with compute capability less than SM_53, but t
he device containing input half tensor only has SM_52

**Comment by TeriosKrim** [comment]
Dumb question but how would I go about that as I use pinokio to setup everything for me so I'm not sure how to do things

**Comment by SWivid** [comment]
Hi @TeriosKrim if it's possible to do modifications in pinokio inside files?
Just comment out these lines in `F5-TTS/src/f5_tts/infer/utils_infer.py`
https://github.com/SWivid/F5-TTS/blob/6d044f10b0f6b3a7b84844dfbc995382bc1a26b4/src/f5_tts/infer/utils_infer.py#L118-L119
(add '#' before these codes)

will slow down a bit inference speed if device not support fp16

**Comment by ZhikangNiu** [comment]
I will close this issue and feel free to ask questions

**Comment by TeriosKrim** [comment]
@SWivid that worked thanks!
