### ISSUE TITLE
KeyError: 'logger' when I create a new project from UI

### ISSUE THREAD

**Issue by AmeyaGawde326** [SWivid/F5-TTS#331]
Traceback (most recent call last):
  File "d:\Documents\Ai\F5-TTS\.venv\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Documents\Ai\F5-TTS\.venv\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Documents\Ai\F5-TTS\.venv\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Documents\Ai\F5-TTS\.venv\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Documents\Ai\F5-TTS\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Documents\Ai\F5-TTS\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "d:\Documents\Ai\F5-TTS\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Documents\Ai\F5-TTS\.venv\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Ai\F5-TTS\src\f5_tts\train\finetune_gradio.py", line 167, in load_settings
    settings["logger"],
    ~~~~~~~~^^^^^^^^^^
KeyError: 'logger'

**Comment by lpscr** [comment]
@AmeyaGawde326 after new update there is new now value **lorger**
go to your ckpts/project_name/ there is file setting.json open
and add

```
    "logger": "tensorboard"
}
```
or just remove it simple the setting.json 
or wait i just update now @SWivid check my pull request

**Comment by AmeyaGawde326** [comment]
Yups works now , ill close the issue
