### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for EMA

### ISSUE THREAD

**Issue by russell-shu** [SWivid/F5-TTS#337]
求助，是加载模型的代码不对吗，我只改了cache_path为本地的绝对路径

Traceback (most recent call last):
  File "/data/russell/F5-TTS/src/f5_tts/train/finetune_cli.py", line 161, in <module>
    main()
  File "/data/russell/F5-TTS/src/f5_tts/train/finetune_cli.py", line 154, in main
    trainer.train(
  File "/data/russell/F5-TTS/src/f5_tts/model/trainer.py", line 248, in train
    start_step = self.load_checkpoint()
  File "/data/russell/F5-TTS/src/f5_tts/model/trainer.py", line 168, in load_checkpoint
    self.ema_model.load_state_dict(checkpoint["ema_model_state_dict"])
  File "/data/env/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for EMA:
        size mismatch for ema_model.transformer.text_embed.text_embed.weight: copying a param with shape torch.Size([2546, 512]) from checkpoint, the shape in current model is torch.Size([3413, 512]).
Traceback (most recent call last):
  File "/data/env/f5-tts/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/data/env/f5-tts/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/data/env/f5-tts/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/data/env/f5-tts/lib/python3.10/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/data/env/f5-tts/bin/python', 'src/f5_tts/train/finetune_cli.py', '--exp_name', 'F5TTS_Base', '--learning_rate', '1e-05', '--batch_size_per_gpu', '2400', '--batch_size_type', 'frame', '--max_samples', '64', '--grad_accumulation_steps', '1', '--max_grad_norm', '1', '--epochs', '18107', '--num_warmup_updates', '14', '--save_per_updates', '26', '--last_per_steps', '6', '--dataset_name', 'yn_1030', '--finetune', 'True', '--tokenizer', 'pinyin', '--log_samples', 'True', '--logger', 'wandb']' returned non-zero exit status 1.

**Comment by russell-shu** [comment]
非常感谢，果然是我改了vocab的原因

> vocab大小不对，如果想finetune的话，不要更改vocab

**Comment by ZhikangNiu** [comment]
great
