### ISSUE TITLE
Errors saying I did not provide transcription for audio

### ISSUE THREAD

**Issue by bbecausereasonss** [SWivid/F5-TTS#35]
Not sure what's going on, but it's saying I did not provide a transcription; then it says it will do it and does nothing. Win11 + Gradio 

Also get this error in Win11 (following all the instructions perfectly)

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\vdrut\Deep\F5-TTS\gradio_app.py", line 4, in <module>
    import torchaudio
  File "C:\Users\vdrut\Deep\F5-TTS\venv\lib\site-packages\torchaudio\__init__.py", line 13, in <module>
    from . import (  # noqa: F401
  File "C:\Users\xxxx\Deep\F5-TTS\venv\lib\site-packages\torchaudio\compliance\__init__.py", line 1, in <module>
    from . import kaldi
  File "C:\Users\xxxx\Deep\F5-TTS\venv\lib\site-packages\torchaudio\compliance\kaldi.py", line 22, in <module>
    EPSILON = torch.tensor(torch.finfo(torch.float).eps)
C:\Users\xxxx\Deep\F5-TTS\venv\lib\site-packages\torchaudio\compliance\kaldi.py:22: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  EPSILON = torch.tensor(torch.finfo(torch.float).eps)

**Comment by bbecausereasonss** [comment]
FYI. Fixed with pip install "numpy<2.0"
