### ISSUE TITLE
Issues with multiple GPUs when using the chat function.

### ISSUE THREAD

**Issue by JAAYapps** [SWivid/F5-TTS#355]
I'm having issues with the voice chat function in F5. I can use the TTS just fine, but the voice chat is errors with an incompatibility with the GPU. I have both an RTX 3090 and a 2080ti. It is not clear what went wrong when trying to use the right GPU or if I can get it to use just my 3090. I have the correct cuda version install which is 12.4. I am using a conda environment with python 3.10.

Traceback (most recent call last):
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/home/jvanderzee/F5-TTS/src/f5_tts/infer/infer_gradio.py", line 584, in process_audio_input
    response = generate_response(conv_state, chat_model_state, chat_tokenizer_state)
  File "/home/jvanderzee/F5-TTS/src/f5_tts/infer/infer_gradio.py", line 68, in generate_response
    generated_ids = model.generate(
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/transformers/generation/utils.py", line 2215, in generate
    result = self._sample(
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/transformers/generation/utils.py", line 3206, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1164, in forward
    outputs = self.model(
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 895, in forward
    layer_outputs = decoder_layer(
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 623, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/jvanderzee/miniconda3/envs/f5-tts/lib/python3.10/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 544, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
RuntimeError: FlashAttention only supports Ampere GPUs or newer.

**Comment by SWivid** [comment]
> if I can get it to use just my 3090

cmd run "nvidia-smi" see at which rank is 3090

if 3090 is rank0, do `CUDA_VISIBLE_DEVICES=0 f5-tts_infer-gradio`

**Comment by SWivid** [comment]
will close this issue, feel free to open if further questions
