### ISSUE TITLE
Finetune error when first checkpoint is generating 

### ISSUE THREAD

**Issue by rikabi89** [SWivid/F5-TTS#364]
`Epoch 17/114158:  70%|#######   | 7/10 [00:46<00:15,  5.06s/step, loss=0.69, step=167]
Epoch 17/114158:  70%|#######   | 7/10 [00:46<00:15,  5.06s/step, loss=0.774, step=168]
Epoch 17/114158:  70%|#######   | 7/10 [00:57<00:24,  8.26s/step, loss=0.774, step=168]
Traceback (most recent call last):
  File "D:\F5-TTS\F5-TTS\src\f5_tts\train\finetune_cli.py", line 161, in <module>
    main()
  File "D:\F5-TTS\F5-TTS\src\f5_tts\train\finetune_cli.py", line 154, in main
    trainer.train(
  File "D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 328, in train
    torchaudio.save(f"{log_samples_path}/step_{global_step}_ref.wav", ref_audio, target_sample_rate)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torchaudio\_backend\utils.py", line 313, in save
    return backend.save(
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torchaudio\_backend\soundfile.py", line 44, in save
    soundfile_backend.save(
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 457, in save
    soundfile.write(file=filepath, data=src, samplerate=sample_rate, subtype=subtype, format=format)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\soundfile.py", line 338, in write
    data = np.asarray(data)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torch\_tensor.py", line 1149, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "D:\F5-TTS\F5-TTS\src\f5_tts\train\finetune_cli.py", line 161, in <module>
    main()
  File "D:\F5-TTS\F5-TTS\src\f5_tts\train\finetune_cli.py", line 154, in main
    trainer.train(
  File "D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 328, in train
    torchaudio.save(f"{log_samples_path}/step_{global_step}_ref.wav", ref_audio, target_sample_rate)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torchaudio\_backend\utils.py", line 313, in save
    return backend.save(
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torchaudio\_backend\soundfile.py", line 44, in save
    soundfile_backend.save(
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 457, in save
    soundfile.write(file=filepath, data=src, samplerate=sample_rate, subtype=subtype, format=format)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\soundfile.py", line 338, in write
    data = np.asarray(data)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torch\_tensor.py", line 1149, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Keyboard interruption in main thread... closing server.
Exception ignored in atexit callback: <function _MultiProcessingDataLoaderIter._clean_up_worker at 0x000002362A013640>
Traceback (most recent call last):
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\torch\utils\data\dataloader.py", line 1598, in _clean_up_worker
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "H:\anaconda3\envs\F5-TTS\lib\multiprocessing\process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "H:\anaconda3\envs\F5-TTS\lib\multiprocessing\popen_spawn_win32.py", line 108, in wait
    res = _winapi.WaitForSingleObject(int(self._handle), msecs)
KeyboardInterrupt:
wandb: ðŸš€ View run F5TTS_Base at: https://wandb.ai/rikabi/trump/runs/joczxjhi
wandb: Find logs at: wandb\run-20241101_135926-joczxjhi\logs
Traceback (most recent call last):
  File "H:\anaconda3\envs\F5-TTS\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "H:\anaconda3\envs\F5-TTS\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\anaconda3\envs\F5-TTS\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\accelerate\commands\launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "H:\anaconda3\envs\F5-TTS\lib\site-packages\accelerate\commands\launch.py", line 760, in simple_launcher
    process.wait()
  File "H:\anaconda3\envs\F5-TTS\lib\subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "H:\anaconda3\envs\F5-TTS\lib\subprocess.py", line 1506, in _wait
    result = _winapi.WaitForSingleObject(self._handle,`

**Comment by SWivid** [comment]
@ZhikangNiu 
"D:\F5-TTS\F5-TTS\src\f5_tts\model\trainer.py", line 327-328 339-340
need fix for backward compatibility

**Comment by ZhikangNiu** [comment]
OK, I will close this issue and merge this pr
