### ISSUE TITLE
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:1089/')

### ISSUE THREAD

**Issue by jakeytan** [SWivid/F5-TTS#381]
(f5)$ f5-tts_infer-gradio 
Traceback (most recent call last):
  File "/home/jk/miniconda3/envs/f5/bin/f5-tts_infer-gradio", line 5, in <module>
    from f5_tts.infer.infer_gradio import main
  File "/media/jk/000BCAF400087F74/F5-TTS/F5-TTS/src/f5_tts/infer/infer_gradio.py", line 8, in <module>
    import gradio as gr
  File "/home/jk/miniconda3/envs/f5/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/jk/miniconda3/envs/f5/lib/python3.10/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/jk/miniconda3/envs/f5/lib/python3.10/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import Component, FormComponent
  File "/home/jk/miniconda3/envs/f5/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/jk/miniconda3/envs/f5/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 13, in <module>
    from gradio import processing_utils, utils
  File "/home/jk/miniconda3/envs/f5/lib/python3.10/site-packages/gradio/processing_utils.py", line 99, in <module>
    sync_client = httpx.Client(transport=sync_transport)
  File "/home/jk/miniconda3/envs/f5/lib/python3.10/site-packages/httpx/_client.py", line 693, in __init__
    proxy_map = self._get_proxy_map(proxies or proxy, allow_env_proxies)
  File "/home/jk/miniconda3/envs/f5/lib/python3.10/site-packages/httpx/_client.py", line 218, in _get_proxy_map
    return {
  File "/home/jk/miniconda3/envs/f5/lib/python3.10/site-packages/httpx/_client.py", line 219, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/jk/miniconda3/envs/f5/lib/python3.10/site-packages/httpx/_config.py", line 338, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:1089/')

**Comment by SWivid** [comment]
are you using system proxy?

**Comment by jakeytan** [comment]
> are you using system proxy?

yes ! qv2ray

**Comment by SWivid** [comment]
so it's a network problem, try using a proxy that will not take over all system (e.g. not using tunnel mode)
and if you could connect to hf directly, not using proxy.

**Comment by jakeytan** [comment]
ok,it is going on already, thanks a lot !

**Comment by SWivid** [comment]
ok, that's great~

**Comment by jakeytan** [comment]
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by SWivid** [comment]
> huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

yeh, so cannot connect directly, then try using a proxy that will not take over all system (e.g. not using tunnel mode)
or you can manually download the ckpt files, and following instruction in readme to load the local ckpt file.
