### ISSUE TITLE
ZLUDA support for AMD GPU

### ISSUE THREAD

**Issue by edemirkan** [SWivid/F5-TTS#414]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Windows 11, AMD Radeon RX7800 XT, Python 3.10, torch==2.3.0+cu118, torchaudio==2.3.0+cu118

### Steps to Reproduce

1. Create a new Python 3.10 virtual environment
2. Clone the repository, install as local editable and properly setup
3. Run the following batch to install ZLUDA and patch Torch dlls
```
echo  ::  %time:~0,8%  ::  - Patching ZLUDA (Zluda 3.8.4 for HIP SDK 5.7)
curl -o zluda.zip -L https://github.com/lshqqytiger/ZLUDA/releases/download/rel.c0804ca624963aab420cb418412b1c7fbae3454b/ZLUDA-windows-rocm5-amd64.zip
tar -xf zluda.zip
del zluda.zip
copy zluda\cublas.dll venv\Lib\site-packages\torch\lib\cublas64_11.dll /y >NUL
copy zluda\cusparse.dll venv\Lib\site-packages\torch\lib\cusparse64_11.dll /y >NUL
copy zluda\nvrtc.dll venv\Lib\site-packages\torch\lib\nvrtc64_112_0.dll /y >NUL
@echo  ::  %time:~0,8%  ::  - ZLUDA is patched.
echo. 
```
4. `Update infer_gradio.py` to enable ZLUDA

```
def main(port, host, share, api):
    global app
    print("Starting app...")
    torch_device_name =  get_torch_device_name()
    if "[ZLUDA]" in torch_device_name:
        print(" ")
        print("***----------------------ZLUDA--------------------------***")
        print("  ::  ZLUDA detected, disabling non-supported functions.")
        torch.backends.cudnn.enabled = False
        print("  ::  (cuDNN, flash_sdp, mem_efficient_sdp disabled) ")
        torch.backends.cuda.enable_flash_sdp(False)
        torch.backends.cuda.enable_math_sdp(True)
        torch.backends.cuda.enable_mem_efficient_sdp(False)
        print("***-----------------------------------------------------***")
    print("  ::  Device:", torch_device_name)
    print(" ")
    app.queue(api_open=api).launch(server_name=host, server_port=port, share=share, show_api=api)

def get_torch_device_name():
    device = "N/A"
    device_name = "N/A"
    allocator_backend = "N/A"
    device_major = "N/A"
    try:
        device = torch.device(torch.cuda.current_device())
        device_name = torch.cuda.get_device_name(device)
        allocator_backend = torch.cuda.get_allocator_backend()
        device_major = torch.cuda.get_device_properties(device).major
    except Exception as e:
        print(f"CUDA ERROR: {e}")
    return "{} {} : {} - {}".format(device, device_name, allocator_backend, device_major)
```
5. Start the app as
```
@echo off

set PYTHON="%~dp0/venv/Scripts/python.exe"
set GIT=
set VIRTUAL_ENV=./venv
set COMMANDLINE_ARGS=

set ZLUDA_COMGR_LOG_LEVEL=1
If Not Exist "%VIRTUAL_ENV%\Scripts\activate.bat" Exit /B 1

echo  ::  %time:~0,8%  ::  - Virtual enviroment activation
Call "%VIRTUAL_ENV%\Scripts\activate.bat"

echo *** Checking and updating to new version if possible 
git pull
echo.
.\zluda\zluda.exe -- f5-tts_infer-gradio
pause
```

### ✔️ Expected Behavior

I know this a super long shot and probably not supported but, I'd like open up a discussion anyway - and hopefully get some pointers. What I'm trying to do is setting up f5-TTS running under AMD cards using ZLUDA using (Zluda 3.8.4 for HIP SDK 5.7)

As per the provided log under Actual Behavior section, I was able to get the UI and the rest of the flow started but getting an error message during  transcribe step; 

```
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR
```

I narrowed the problem down to this section, in `utils_infer.py` but would be glad for your input regarding what I can check for this to work with ZLUDA.
```
def initialize_asr_pipeline(device=device, dtype=None):
    if dtype is None:
        dtype = (
            torch.float16 if device == "cuda" and torch.cuda.get_device_properties(device).major >= 6 else torch.float32
        )
    global asr_pipe
    asr_pipe = pipeline(
        "automatic-speech-recognition",
        model="openai/whisper-large-v3-turbo",
        torch_dtype=dtype,
        device=device,
    )
```

thanks!

### ❌ Actual Behavior

 ::   0:02:39  ::  - Virtual enviroment activation
*** Checking and updating to new version if possible
Already up to date.

Download Vocos from huggingface charactr/vocos-mel-24khz

vocab :  E:\code\projects\ai\F5-TTS-Zluda\src\f5_tts\infer\examples\vocab.txt
tokenizer :  custom
model :  C:\Users\avefe\.cache\huggingface\hub\models--SWivid--F5-TTS\snapshots\995ff41929c08ff968786b448a384330438b5cb6\F5TTS_Base\model_1200000.safetensors

vocab :  E:\code\projects\ai\F5-TTS-Zluda\src\f5_tts\infer\examples\vocab.txt
tokenizer :  custom
model :  C:\Users\avefe\.cache\huggingface\hub\models--SWivid--E2-TTS\snapshots\98016df3e24487aad803aff506335caba8414195\E2TTS_Base\model_1200000.safetensors

Starting app...

***----------------------ZLUDA--------------------------***
  ::  ZLUDA detected, disabling non-supported functions.
  ::  (cuDNN, flash_sdp, mem_efficient_sdp disabled)
***-----------------------------------------------------***
  ::  Device: cuda:0 AMD Radeon RX 7800 XT [ZLUDA] : native - 8

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\transformers\models\whisper\generation_whisper.py:509: FutureWarning: The input name `inputs` is deprecated. Please make sure to use `input_features` instead.
  warnings.warn(
You have passed task=transcribe, but also have set `forced_decoder_ids` to [[1, None], [2, 50360]] which creates a conflict. `forced_decoder_ids` will be ignored in favor of task=transcribe.
E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\transformers\models\whisper\modeling_whisper.py:545: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.43.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
gen_text 0 today is a good day to die!
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\avefe\AppData\Local\Temp\jieba.cache
Loading model cost 0.442 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "E:\code\projects\ai\F5-TTS-Zluda\src\f5_tts\infer\infer_gradio.py", line 93, in infer
    final_wave, final_sample_rate, combined_spectrogram = infer_process(
  File "E:\code\projects\ai\F5-TTS-Zluda\src\f5_tts\infer\utils_infer.py", line 348, in infer_process
    return infer_batch_process(
  File "E:\code\projects\ai\F5-TTS-Zluda\src\f5_tts\infer\utils_infer.py", line 420, in infer_batch_process
    generated, _ = model_obj.sample(
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\code\projects\ai\F5-TTS-Zluda\src\f5_tts\model\cfm.py", line 104, in sample
    cond = self.mel_spec(cond)
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\code\projects\ai\F5-TTS-Zluda\src\f5_tts\model\modules.py", line 134, in forward
    mel = self.extractor(
  File "E:\code\projects\ai\F5-TTS-Zluda\src\f5_tts\model\modules.py", line 99, in get_vocos_mel_spectrogram
    mel = mel_stft(waveform)
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torchaudio\transforms\_transforms.py", line 619, in forward
    specgram = self.spectrogram(waveform)
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torchaudio\transforms\_transforms.py", line 110, in forward
    return F.spectrogram(
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torchaudio\functional\functional.py", line 126, in spectrogram
    spec_f = torch.stft(
  File "E:\code\projects\ai\F5-TTS-Zluda\venv\lib\site-packages\torch\functional.py", line 665, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

**Comment by edemirkan** [comment]
I labeled this as bug as mistake, probably `Help Wanted` is a better label as there's no really a problem with the code from cuda perspective.
