### ISSUE TITLE
【BUG】待合成文本没有标点符号结尾时，合成失败

### ISSUE THREAD

**Issue by Ikaros-521** [SWivid/F5-TTS#43]
报错
```
Traceback (most recent call last):
  File "F:\F5-TTS\Miniconda3\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "F:\F5-TTS\Miniconda3\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\F5-TTS\Miniconda3\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "F:\F5-TTS\Miniconda3\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "F:\F5-TTS\Miniconda3\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\F5-TTS\Miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "F:\F5-TTS\Miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "F:\F5-TTS\Miniconda3\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "F:\F5-TTS\gradio_app.py", line 401, in infer_with_custom_split
    return infer(ref_audio_orig, ref_text, gen_text, exp_name, remove_silence)
  File "F:\F5-TTS\gradio_app.py", line 302, in infer
    return infer_batch(ref_audio, ref_text, gen_text_batches, exp_name, remove_silence)
  File "F:\F5-TTS\gradio_app.py", line 262, in infer_batch
    final_wave = np.concatenate(generated_waves)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
```

这个切分差点意思，没有标点符号的情况下，有必要补上或者直接整句合成
```
gen_text_batches = split_text_into_batches(gen_text)
```
追加
```
if gen_text_batches is None or len(gen_text_batches) == 0:
        gen_text_batches = [gen_text]
```

**Comment by SWivid** [comment]
我对中文支持追加修改了，试试这个 615d183a0d87ac1feaf628c97cdaa21a6954f04a

**Comment by Ikaros-521** [comment]
> 我对中文支持追加修改了，试试这个 [615d183](https://github.com/SWivid/F5-TTS/commit/615d183a0d87ac1feaf628c97cdaa21a6954f04a)

标点符号问题依旧，合成倒是没啥问题

**Comment by SWivid** [comment]
加上提及的修改了~
