### ISSUE TITLE
The operator 'aten::unfold_backward' is not currently implemented for the MPS device

### ISSUE THREAD

**Issue by cocktailpeanut** [SWivid/F5-TTS#443]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

macOS 14.4.1, Python 3.10, torch==2.4.1, torchaudio==2.4.1

### Steps to Reproduce

1. On a Mac, run the exact same install steps as before (which used to work)
2. Start the gradio inference UI with `f5-tts_infer-gradio`
3. Try generating something => It fails with the error.

### ✔️ Expected Behavior

used to work without having to set environment variables

### ❌ Actual Behavior

The latest code throws a `The operator 'aten::unfold_backward' is not currently implemented for the MPS device` error when running both the inference and the training UI.

I can work around it by setting the `PYTOCH_ENABLE_MPS_FALLBACK` environment variable to `1`, but just curious if this is expected.

Previously it used to work without having to set this environment variable. Here's the full log:

```
Traceback (most recent call last):
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/src/f5_tts/infer/infer_gradio.py", line 203, in basic_tts
    audio_out, spectrogram_path, ref_text_out = infer(
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/src/f5_tts/infer/infer_gradio.py", line 122, in infer
    final_wave, final_sample_rate, combined_spectrogram = infer_process(
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/src/f5_tts/infer/utils_infer.py", line 349, in infer_process
    return infer_batch_process(
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/src/f5_tts/infer/utils_infer.py", line 434, in infer_batch_process
    generated_wave = vocoder.decode(generated_mel_spec)
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/vocos/pretrained.py", line 113, in decode
    audio_output = self.head(x)
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/vocos/heads.py", line 68, in forward
    audio = self.istft(S)
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/x/pinokio/api/e2-f5-tts.git/app/env/lib/python3.10/site-packages/vocos/spectral_ops.py", line 46, in forward
    return torch.istft(spec, self.n_fft, self.hop_length, self.win_length, self.window, center=True)
NotImplementedError: The operator 'aten::unfold_backward' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

**Comment by SWivid** [comment]
Hi @cocktailpeanut. Yes, it is expected to work with `PYTOCH_ENABLE_MPS_FALLBACK=1` in cmd,
Probably for reason that in the update introducing bigvgan, the vocoder decode operation is moved to gpu, while istft is fine with cpu previously.

Check if add 
```python
if device == "mps":
    os.environ["PYTOCH_ENABLE_MPS_FALLBACK"] = "1"
```
below the line https://github.com/SWivid/F5-TTS/blob/3fcdbc70b4a9d4299e1ecd0b5a1c35209f23fd69/src/f5_tts/infer/utils_infer.py#L34 will work without manually set env in cmd.

If work, feel free to PR, or tell us and we'll add a commit to fix it~

**Comment by SWivid** [comment]
Close as solved.

**Comment by JiajunDou** [comment]
![sc](https://github.com/user-attachments/assets/462862b3-b0ff-411c-ab45-53106bf096be)
This problem is still unresolved

**Comment by SWivid** [comment]
@JiajunDou It's just warning...

**Comment by rizhangdev** [comment]
The new PR did not resolve this problem for, but running this in the cmd line before running `$: f5-tts_infer-gradio` resolved it.
```
$: export PYTORCH_ENABLE_MPS_FALLBACK=1
```
If this is only true on my machine, I'm not sure why that is.

**Comment by jonnyjohnson1** [comment]
Anyone figure this out?
