### ISSUE TITLE
Newest batch commit broke inference

### ISSUE THREAD

**Issue by jpgallegoar** [SWivid/F5-TTS#45]
Traceback (most recent call last):
  File "C:\Users\thega\miniconda3\envs\tts\lib\site-packages\gradio\queueing.py", line 622, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\thega\miniconda3\envs\tts\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\thega\miniconda3\envs\tts\lib\site-packages\gradio\blocks.py", line 2016, in process_api
    result = await self.call_function(
  File "C:\Users\thega\miniconda3\envs\tts\lib\site-packages\gradio\blocks.py", line 1569, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\thega\miniconda3\envs\tts\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\thega\miniconda3\envs\tts\lib\site-packages\anyio\_backends\_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "C:\Users\thega\miniconda3\envs\tts\lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "C:\Users\thega\miniconda3\envs\tts\lib\site-packages\gradio\utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI\F5-TTS\gradio_app.py", line 326, in infer
    return infer_batch(ref_audio, ref_text, gen_text_batches, exp_name, remove_silence)
  File "D:\AI\F5-TTS\gradio_app.py", line 252, in infer_batch
    final_wave = np.concatenate(generated_waves)
    
    Newest batch commit broke inference in some cases. I got this error with one specific prompt, and by adding a "." at the end of the prompt, the error went away and inference worked again. I think it's better if you disable batching for generations smaller than 200 chars, or fix this issue.

**Comment by SWivid** [comment]
Thanks for report.
Would it be fine with current version ?

**Comment by jpgallegoar** [comment]
Hello, thank you very much for the quick response and commit, it has been fixed.
