### ISSUE TITLE
load finetune data

### ISSUE THREAD

**Issue by southwindyong** [SWivid/F5-TTS#459]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

train on 4 a800

### Steps to Reproduce

I encountered an issue when trying to load my fine-tuned checkpoint. During the load_state_dict() call, I received the following error:
```
Traceback (most recent call last):
  File "/remote-home1/ycyuan/TTS/F5-TTS/inference.py", line 151, in <module>
    infer_tts()
  File "/remote-home1/ycyuan/TTS/F5-TTS/inference.py", line 72, in infer_tts
    ema_model = load_model(model_cls, model_cfg, ckpt_file, mel_spec_type=vocoder_name, vocab_file=vocab_file)
  File "/remote-home1/ycyuan/TTS/F5-TTS/src/f5_tts/infer/utils_infer.py", line 216, in load_model
    model = load_checkpoint(model, ckpt_path, device, dtype=dtype, use_ema=use_ema)
  File "/remote-home1/ycyuan/TTS/F5-TTS/src/f5_tts/infer/utils_infer.py", line 168, in load_checkpoint
    model.load_state_dict(checkpoint["model_state_dict"])
  File "/remote-home1/ycyuan/conda/anaconda3/envs/f5-tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CFM:
    Missing key(s) in state_dict: "transformer.time_embed.time_mlp.0.weight", "transformer.time_embed.time_mlp.0.bias", "transformer.time_embed.time_mlp.2.weight", "transformer.time_embed.time_mlp.2.bias", "transformer.text_embed.text_embed.weight", "transformer.text_embed.text_blocks.0.dwconv.weight", "transformer.text_embed.text_blocks.0.dwconv.bias", "transformer.text_embed.text_blocks.0.norm.weight", "transformer.text_embed.text_blocks.0.norm.bias", "transformer.text_embed.text_blocks.0.pwconv1.weight", "transformer.text_embed.text_blocks.0.pwconv1.bias", "transformer.text_embed.text_blocks.0.grn.gamma", "transformer.text_embed.text_blocks.0.grn.beta", "transformer.text_embed.text_blocks.0.pwconv2.weight", "transformer.text_embed.text_blocks.0.pwconv2.bias", "transformer.text_embed.text_blocks.1.dwconv.weight", "transformer.text_embed.text_blocks.1.dwconv.bias", "transformer.text_embed.text_blocks.1.norm.weight", "transformer.text_embed.text_blocks.1.norm.bias"...
    Unexpected key(s) in state_dict: "module.transformer.time_embed.time_mlp.0.weight", "module.transformer.time_embed.time_mlp.0.bias", "module.transformer.time_embed.time_mlp.2.weight", "module.transformer.time_embed.time_mlp.2.bias", "module.transformer.text_embed.text_embed.weight", "module.transformer.text_embed.text_blocks.0.dwconv.weight", "module.transformer.text_embed.text_blocks.0.dwconv.bias", "module.transformer.text_embed.text_blocks.0.norm.weight", "module.transformer.text_embed.text_blocks.0.norm.bias", "module.transformer.text_embed.text_blocks.0.pwconv1.weight", "module.transformer.text_embed.text_blocks.0.pwconv1.bias", "module.transformer.text_embed.text_blocks.0.grn.gamma", "module.transformer.text_embed.text_blocks.0.grn.beta",...
```
However, when I print the checkpoint['model_state_dict'], it seems correct and shows all the keys expected:
```
OrderedDict([('transformer.time_embed.time_mlp.0.weight', tensor([[-0.0007, -0.0009, -0.0007,  ..., -0.0355,  0.0119,  0.0061], ...], device='cuda:3')),
            ('transformer.time_embed.time_mlp.0.bias', tensor([ 0.0139,  0.0171,  0.0399,  ..., -0.0508,  0.0258, -0.0191], device='cuda:3'))]),....
```
However, when I attempt to load the checkpoint without any wrapping, the model loading fails due to the error above. If I wrap the model with DataParallel before loading the checkpoint (like this: model = torch.nn.DataParallel(model)), the loading works fine, but this leads to subsequent errors during inference.

Additionally, I have tried to remove the module prefix using the following function:
```
def remove_module_prefix(state_dict):
    new_state_dict = {}
    for k, v in state_dict.items():
        # Remove the 'module.' prefix
        print(k)
        new_k = k.replace('module.', '') if 'module.' in k else k
        new_state_dict[new_k] = v
    return new_state_dict
```
However, this approach does not work because, when I print the keys, they don't actually contain the module. prefix. Despite this, when loading the checkpoint, I still encounter a mismatch error regarding the module. prefix.

I have not modified the checkpoint saving function. Here’s the relevant code that I use to save checkpoints:
```
def save_checkpoint(self, step, last=False):
    self.accelerator.wait_for_everyone()
    if self.is_main:
        checkpoint = dict(
            model_state_dict=self.accelerator.unwrap_model(self.model).state_dict(),
            optimizer_state_dict=self.accelerator.unwrap_model(self.optimizer).state_dict(),
            ema_model_state_dict=self.ema_model.state_dict(),
            scheduler_state_dict=self.scheduler.state_dict(),
            step=step,
        )
        if not os.path.exists(self.checkpoint_path):
            os.makedirs(self.checkpoint_path)
        rank = self.accelerator.process_index

        if rank == 0:
            if last:
                self.accelerator.save(checkpoint, f"{self.save_ckpt_path}/model_last.pt")
                print(f"Saved last checkpoint at step {step}")
            else:
                self.accelerator.save(checkpoint, f"{self.save_ckpt_path}/model_{step}.pt")
```

Is there a way to handle the mismatch of the module. prefix in the checkpoint file?

**Comment by SWivid** [comment]
maybe you could provide the additional `File "/remote-home1/ycyuan/TTS/F5-TTS/inference.py"` for more info to figure out the issue.

**Comment by southwindyong** [comment]
This is the file of ``/remote-home1/ycyuan/TTS/F5-TTS/inference.py``
```
import os
import random
import json
import codecs
import numpy as np
import soundfile as sf
import tomli
from pathlib import Path
from f5_tts.infer.utils_infer import (
    infer_process,
    load_model,
    load_vocoder,
    preprocess_ref_audio_text,
    remove_silence_for_generated_wav,
)
from f5_tts.model import DiT, UNetT
import re

def infer_tts():
    # Directly specify the variables without argparse
    print("开始 TTS 推理过程...")

    config_path = Path("f5_tts") / "infer/examples/basic" / "basic.toml"  
    model = "F5-TTS"  # Choose "F5-TTS" or "E2-TTS"
    ckpt_file = "/remote-home1/ycyuan/TTS/F5-TTS/ckpts/F5TTS_Base/libritts_25s_1/model_last.pt"  # Provide the path to checkpoint if necessary
    vocab_file = ""  # Provide the vocab file path if necessary
    text_dir = "/remote-home1/ycyuan/TTS/fish-speech/prompt/libritts_text_2-6"  # Text directory
    audio_dir = "/remote-home1/ycyuan/TTS/fish-speech/prompt/libritts_prompt_2_10s"  # Audio directory
    output_dir = "./generate_data/libritts_25s_1"  # Path to output folder
    remove_silence = False  # Whether to remove silence from generated audio
    vocoder_name = "vocos"  # Choose between "vocos" or "bigvgan"
    load_vocoder_from_local = False  # Whether to load vocoder from local path
    speed = 1.0  # Adjust audio generation speed (default is 1.0)

    # Load configuration from the specified TOML file
    print(f"加载配置文件 {config_path}...")
    config = tomli.load(open(config_path, "rb"))
    
    # Use provided values or defaults from the config file
    output_dir = output_dir if output_dir else config["output_dir"]
    model = model if model else config["model"]
    ckpt_file = ckpt_file if ckpt_file else ""
    vocab_file = vocab_file if vocab_file else ""
    remove_silence = remove_silence if remove_silence else config["remove_silence"]
    speed = speed
    wave_path = Path(output_dir) / "infer_cli_out.wav"
    
    # Set vocoder local path based on the selected vocoder
    print(f"选择的 vocoder 模型: {vocoder_name}...")
    if vocoder_name == "vocos":
        vocoder_local_path = "../checkpoints/vocos-mel-24khz"
    elif vocoder_name == "bigvgan":
        vocoder_local_path = "../checkpoints/bigvgan_v2_24khz_100band_256x"
    
    # Load the vocoder model
    print("加载 vocoder 模型...")
    vocoder = load_vocoder(vocoder_name=vocoder_name, is_local=load_vocoder_from_local, local_path=vocoder_local_path)

    # Load the TTS model
    print(f"加载 TTS 模型: {model}...")
    if model == "F5-TTS":
        model_cls = DiT
        model_cfg = dict(dim=1024, depth=22, heads=16, ff_mult=2, text_dim=512, conv_layers=4)
        if ckpt_file == "":
            repo_name = "F5-TTS"
            exp_name = "F5TTS_Base"
            ckpt_step = 1200000
            ckpt_file = str(cached_path(f"hf://SWivid/{repo_name}/{exp_name}/model_{ckpt_step}.safetensors"))
    elif model == "E2-TTS":
        model_cls = UNetT
        model_cfg = dict(dim=1024, depth=24, heads=16, ff_mult=4)
        if ckpt_file == "":
            repo_name = "E2-TTS"
            exp_name = "E2TTS_Base"
            ckpt_step = 1200000
            ckpt_file = str(cached_path(f"hf://SWivid/{repo_name}/{exp_name}/model_{ckpt_step}.safetensors"))
    
    # Initialize the model
    print(f"使用 {model} 模型进行推理...")
    ema_model = load_model(model_cls, model_cfg, ckpt_file, mel_spec_type=vocoder_name, vocab_file=vocab_file)
    print("模型加载成功。")

    # Load a random JSON file containing text
    print(f"从 {text_dir} 中加载随机 JSON 文件...")
    json_files = [f for f in os.listdir(text_dir) if f.endswith('.json')]
    random_json_file = random.choice(json_files)
    json_file_path = os.path.join(text_dir, random_json_file)

    with open(json_file_path, 'r') as file:
        json_data = json.load(file)
        text = json_data["完整文本"]
        text_turns = json_data["文件数"]

    # From the audio directory, select a random folder and corresponding audio file
    print(f"从 {audio_dir} 中选择一个随机文件夹...")
    folders = [f for f in os.listdir(audio_dir) if os.path.isdir(os.path.join(audio_dir, f))]
    while True:
        random_folder = random.choice(folders)
        folder_path = os.path.join(audio_dir, random_folder)
        lab_files = [f for f in os.listdir(folder_path) if f.endswith('.lab')]
        if not lab_files:
            continue  # Skip folders without `.lab` files

        random_lab_file = random.choice(lab_files)
        lab_file_path = os.path.join(folder_path, random_lab_file)

        # Read the corresponding `.lab` file to get prompt text
        with open(lab_file_path, 'r') as lab_file:
            prompt_text = lab_file.read().strip()
        prompt_turns = len(prompt_text.splitlines())  # Number of lines = number of turns

        if text_turns % 2 == prompt_turns % 2 and prompt_turns <= 4:  # Ensure matching turns and prompt_turns <= 4
            break

    # Choose the corresponding audio file
    print(f"选择的音频文件: {random_lab_file}...")
    audio_file = random_lab_file.replace('.lab', '.wav')
    ref_audio = os.path.join(folder_path, audio_file)
    if not os.path.exists(ref_audio):
        raise FileNotFoundError(f"未找到音频文件 {ref_audio}")

    # Call the inference process
    def main_process(ref_audio, text, gen_text, model_obj, mel_spec_type, remove_silence, speed):
        print(f"正在生成音频: {text}")
        generated_audio_segments = []
        reg1 = r"(?=\[\w+\])"
        chunks = re.split(reg1, gen_text)
        reg2 = r"\[(\w+)\]"

        # Process each chunk of the generated text
        for text_chunk in chunks:
            if not text_chunk.strip():
                continue
            match = re.match(reg2, text_chunk)
            if match:
                voice = match[1]
            else:
                print("没有找到语音标签，使用默认语音。")
                voice = "main"
            
            print(f"语音选择: {voice}")
            gen_text = text_chunk.strip()
            audio, final_sample_rate, spectrogram = infer_process(
                ref_audio, text, gen_text, model_obj, vocoder, mel_spec_type=mel_spec_type, speed=speed
            )
            generated_audio_segments.append(audio)

        if generated_audio_segments:
            final_wave = np.concatenate(generated_audio_segments)

            if not os.path.exists(output_dir):
                os.makedirs(output_dir)

            with open(wave_path, "wb") as f:
                sf.write(f.name, final_wave, final_sample_rate)
                if remove_silence:
                    print("正在去除生成音频中的静音部分...")
                    remove_silence_for_generated_wav(f.name)
                print(f"生成的音频已保存到 {f.name}")

    main_process(ref_audio, text, text, ema_model, vocoder_name, remove_silence, speed)

# Call the infer_tts function to start the process
if __name__ == "__main__":
    infer_tts()
```

**Comment by SWivid** [comment]
> print the checkpoint['model_state_dict'], it seems correct and shows all the keys expected

maybe you have changed the code related with ema_model setup?

try do the removal of the module prefix using the function you got to `checkpoint['ema_model_state_dict']` see if works

**Comment by southwindyong** [comment]
problem solved！ Thanks！
