### ISSUE TITLE
self.accelerator.backward(loss) Error white train model

### ISSUE THREAD

**Issue by enessusan00** [SWivid/F5-TTS#488]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

I'm using macOs 15.1 16GB
python 3.10
everything is up to date.

### Steps to Reproduce

I just followed to README.md in main and finetune

### ✔️ Expected Behavior

output a model

### ❌ Actual Behavior

run command : 
accelerate launch  src/f5_tts/train/finetune_cli.py --exp_name F5TTS_Base --learning_rate 1e-05 --batch_size_per_gpu 9600 --batch_size_type frame --max_samples 14 --grad_accumulation_steps 1 --max_grad_norm 1 --epochs 11 --num_warmup_updates 500 --save_per_updates 10000 --last_per_steps 20000 --dataset_name my_speak1 --finetune True --pretrain /Users/enessusan/Documents/my_work/voice-clone/F5-TTS/ckpts/F5TTS_Base/model_1200000.pt --tokenizer pinyin  --log_samples True --logger wandb 

vocab :  2545

vocoder :  vocos
Using logger: None
Loading dataset ...
Download Vocos from huggingface charactr/vocos-mel-24khz

Sorting with sampler... if slow, check whether dataset is provided with duration:   0%|          | 0/59 [00:00<?, ?it/s]
Sorting with sampler... if slow, check whether dataset is provided with duration: 100%|██████████| 59/59 [00:00<00:00, 191535.55it/s]

Creating dynamic batches with 9600 audio frames per gpu:   0%|          | 0/59 [00:00<?, ?it/s]
Creating dynamic batches with 9600 audio frames per gpu: 100%|██████████| 59/59 [00:00<00:00, 1018370.11it/s]

Epoch 1/11:   0%|          | 0/5 [00:00<?, ?step/s]
Epoch 1/11:   0%|          | 0/5 [00:07<?, ?step/s]
Traceback (most recent call last):
  File "/Users/enessusan/Documents/my_work/voice-clone/F5-TTS/src/f5_tts/train/finetune_cli.py", line 174, in <module>
    main()
  File "/Users/enessusan/Documents/my_work/voice-clone/F5-TTS/src/f5_tts/train/finetune_cli.py", line 167, in main
    trainer.train(
  File "/Users/enessusan/Documents/my_work/voice-clone/F5-TTS/src/f5_tts/model/trainer.py", line 301, in train
    self.accelerator.backward(loss)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/f5-tts/lib/python3.10/site-packages/accelerate/accelerator.py", line 2241, in backward
    loss.backward(**kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/f5-tts/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
    torch.autograd.backward(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/f5-tts/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/f5-tts/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/f5-tts/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/f5-tts/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/f5-tts/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/f5-tts/lib/python3.10/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/homebrew/Caskroom/miniforge/base/envs/f5-tts/bin/python3.10', 'src/f5_tts/train/finetune_cli.py', '--exp_name', 'F5TTS_Base', '--learning_rate', '1e-05', '--batch_size_per_gpu', '9600', '--batch_size_type', 'frame', '--max_samples', '14', '--grad_accumulation_steps', '1', '--max_grad_norm', '1', '--epochs', '11', '--num_warmup_updates', '500', '--save_per_updates', '10000', '--last_per_steps', '20000', '--dataset_name', 'my_speak1', '--finetune', 'True', '--pretrain', '/Users/enessusan/Documents/my_work/voice-clone/F5-TTS/ckpts/F5TTS_Base/model_1200000.pt', '--tokenizer', 'pinyin', '--log_samples', 'True', '--logger', 'wandb']' returned non-zero exit status 1.

**Comment by ZhikangNiu** [comment]
haven't test on macOs, you'd better check https://github.com/lucasnewman/f5-tts-mlx/tree/main or run it on Linux

**Comment by enessusan00** [comment]
It's about the calculating view size i guess. My ram usage up to 20 GB

**Comment by ZhikangNiu** [comment]
Will close this issue, feel free to ask question.
