### ISSUE TITLE
Every time during training I get this error

### ISSUE THREAD

**Issue by destroyandromeda** [SWivid/F5-TTS#521]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

win 11, rtx 3060 12g 

### Steps to Reproduce

```shell
pip install torch==2.3.0+cu121 torchaudio==2.3.0+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
```

Every time during training I get this error

### ✔️ Expected Behavior

train

### ❌ Actual Behavior

```shell
Epoch 2/100:  95%|#########5| 1001/1049 [01:05<?, ?step/s]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Work\F5-TTS\src\f5_tts\train\finetune_cli.py", line 174, in <module>
    main()
  File "C:\Users\User\Documents\Work\F5-TTS\src\f5_tts\train\finetune_cli.py", line 167, in main
    trainer.train(
  File "C:\Users\User\Documents\Work\F5-TTS\src\f5_tts\model\trainer.py", line 295, in train
    for batch in progress_bar:
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\accelerate\data_loader.py", line 552, in __iter__
    current_batch = next(dataloader_iter)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\_utils.py", line 705, in reraise
    raise exception
soundfile.LibsndfileError: <exception str() failed>
```

**Comment by SWivid** [comment]
have you do `pip install -e .`?
maybe also check for `libsndfile`, e.g. `conda install -c conda-forge libsndfile` or `pip install pysoundfile`

**Comment by destroyandromeda** [comment]
> have you do pip install -e .?

yes

> maybe also check for libsndfile, e.g. conda install -c conda-forge libsndfile or pip install pysoundfile


I tried this `pip install pysoundfile` but now I get this error and the training stops


```shell
Epoch 3/500:   9%|8         | 86/982 [01:16<?, ?step/s]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Work\F5-TTS\src\f5_tts\train\finetune_cli.py", line 174, in <module>
    main()
  File "C:\Users\User\Documents\Work\F5-TTS\src\f5_tts\train\finetune_cli.py", line 167, in main
    trainer.train(
  File "C:\Users\User\Documents\Work\F5-TTS\src\f5_tts\model\trainer.py", line 314, in train
    self.optimizer.step()
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\optim\lr_scheduler.py", line 75, in wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\accelerate\optimizer.py", line 171, in step
    self.optimizer.step(closure)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\optim\optimizer.py", line 391, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\bitsandbytes\optim\optimizer.py", line 291, in step
    self.update_step(group, p, gindex, pindex)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\bitsandbytes\optim\optimizer.py", line 520, in update_step
    if state["state1"].dtype == torch.float:
KeyError: 'state1'
```

**Comment by destroyandromeda** [comment]
> bnb_optimizer

This means "Use 8-bit Adam optimizer"?

**Comment by SWivid** [comment]
yes
or if you need it, just take some time searching and to debug

**Comment by destroyandromeda** [comment]
I removed this flag and mixed_precision -> none, the process seems to have started

```shell
Epoch 3/1057:   9%|8         | 86/982 [00:00<?, ?step/s]C:\Users\User\Documents\Work\F5-TTS\src\f5_tts\model\modules.py:436: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  x = F.scaled_dot_product_attention(query, key, value, attn_mask=attn_mask, dropout_p=0.0, is_causal=False)
C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\autograd\graph.py:744: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

Epoch 3/1057:   9%|8         | 86/982 [01:19<?, ?step/s, loss=0.626, step=2051]
Epoch 3/1057:   9%|8         | 87/982 [01:19<19:44:41, 79.42s/step, loss=0.626, step=2051]
Epoch 3/1057:   9%|8         | 87/982 [01:28<19:44:41, 79.42s/step, loss=0.688, step=2052]
Epoch 3/1057:   9%|8         | 88/982 [01:28<9:22:30, 37.75s/step, loss=0.688, step=2052]
Epoch 3/1057:   9%|8         | 88/982 [01:40<9:22:30, 37.75s/step, loss=0.575, step=2053]
Epoch 3/1057:   9%|9         | 89/982 [01:40<6:27:30, 26.04s/step, loss=0.575, step=2053]
Epoch 3/1057:   9%|9         | 89/982 [01:50<6:27:30, 26.04s/step, loss=1.6, step=2054]
Epoch 3/1057:   9%|9         | 90/982 [01:50<4:53:27, 19.74s/step, loss=1.6, step=2054]
Epoch 3/1057:   9%|9         | 90/982 [02:00<4:53:27, 19.74s/step, loss=0.643, step=2055]
Epoch 3/1057:   9%|9         | 91/982 [02:00<4:03:18, 16.38s/step, loss=0.643, step=2055]
Epoch 3/1057:   9%|9         | 91/982 [02:09<4:03:18, 16.38s/step, loss=0.665, step=2056]
```

**Comment by destroyandromeda** [comment]
Unfortunately, training is still interrupted

```shell
Epoch 3/1057:   0%|          | 4/1049 [01:53<8:12:32, 28.28s/step, loss=0.611, step=2102]
Traceback (most recent call last):
  File "C:\Users\User\Documents\Work\F5-TTS\src\f5_tts\train\finetune_cli.py", line 174, in <module>
    main()
  File "C:\Users\User\Documents\Work\F5-TTS\src\f5_tts\train\finetune_cli.py", line 167, in main
    trainer.train(
  File "C:\Users\User\Documents\Work\F5-TTS\src\f5_tts\model\trainer.py", line 309, in train
    self.accelerator.backward(loss)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\accelerate\accelerator.py", line 2241, in backward
    loss.backward(**kwargs)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\autograd\__init__.py", line 267, in backward
    _engine_run_backward(
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\autograd\graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Keyboard interruption in main thread... closing server.
Exception ignored in atexit callback: <function _MultiProcessingDataLoaderIter._clean_up_worker at 0x000001ADE8EEF9A0>
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\torch\utils\data\dataloader.py", line 1473, in _clean_up_worker
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "C:\Users\User\.conda\envs\f5-tts\lib\multiprocessing\process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "C:\Users\User\.conda\envs\f5-tts\lib\multiprocessing\popen_spawn_win32.py", line 108, in wait
    res = _winapi.WaitForSingleObject(int(self._handle), msecs)
KeyboardInterrupt:
Traceback (most recent call last):
  File "C:\Users\User\.conda\envs\f5-tts\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\.conda\envs\f5-tts\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\.conda\envs\f5-tts\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\accelerate\commands\launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "C:\Users\User\.conda\envs\f5-tts\lib\site-packages\accelerate\commands\launch.py", line 760, in simple_launcher
    process.wait()
  File "C:\Users\User\.conda\envs\f5-tts\lib\subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "C:\Users\User\.conda\envs\f5-tts\lib\subprocess.py", line 1506, in _wait
    result = _winapi.WaitForSingleObject(self._handle,
KeyboardInterrupt```

**Comment by SWivid** [comment]
![1732455276356](https://github.com/user-attachments/assets/ee93b3ce-c9e7-4a99-babe-959809421fe0)
need detailed steps and thought better for yourself to debug since seems configuration problem and not with our repo
