### ISSUE TITLE
Training Tamil Language from Scratch

### ISSUE THREAD

**Issue by sam4muzix** [SWivid/F5-TTS#531]
### Checks

- [X] This template is only for feature request.
- [X] I have thoroughly reviewed the project documentation but couldn't find any relevant information that meets my needs.
- [X] I have searched for existing issues, including closed ones, and found not discussion yet.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### 1. Is this request related to a challenge you're experiencing? Tell us your story.

I tried to finetune tamil dataset but results are partial. so i started to prepare for training from scratch. please help on how to train from scratch. 

### 2. What is your suggested solution?

gradio webui for training from scratch.

### 4. Can you help us with this feature?

- [X] I am interested in contributing to this feature.

**Comment by sam4muzix** [comment]
> 1. prepare your dataset and your vocab
> 
> 2. `accelerate config`
> 
> 3. update your config in src/f5_tts/train/train.py
> 
> 4. accelerate launch src/f5_tts/train/train.py
> 
> 
> 
> check [src/f5_tts/train/train.py](https://github.com/SWivid/F5-TTS/tree/main/src/f5_tts/train#1-training-script-used-for-pretrained-model) and  https://github.com/SWivid/F5-TTS/blob/d8e622f0043678c57c47ad520aed0265ee73f30b/src/f5_tts/train/train.py#L18-L37

I tried to train with this train.py along with the path mentions. But i get this error repeatedly.

(venv) D:\AI_Programs\PROJECTS\F5\F5-TTS>accelerate launch src/f5_tts/train/train.py
Traceback (most recent call last):
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\src\f5_tts\train\train.py", line 104, in <module>
    main()
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\src\f5_tts\train\train.py", line 56, in main
    tokenizer_path = tokenizer_path
                     ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'tokenizer_path' where it is not associated with a value
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\venv\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\venv\Lib\site-packages\accelerate\commands\launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "D:\AI_Programs\PROJECTS\F5\F5-TTS\venv\Lib\site-packages\accelerate\commands\launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\AI_Programs\\PROJECTS\\F5\\F5-TTS\\venv\\Scripts\\python.exe', 'src/f5_tts/train/train.py']' returned non-zero exit status 1.

**Comment by sam4muzix** [comment]
I have completed the training with custom vocab. But unable to inference it. please help. Should i use the trained model as base model and fine tune it or can i use it for testing.?
