### ISSUE TITLE
Gradio Interface showing Error

### ISSUE THREAD

**Issue by FierceJDM** [SWivid/F5-TTS#555]
### Checks

- [x] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Python 3.11.6 , torch==2.3.0+cu118 , gradio==5.7.1

### Steps to Reproduce

0- Clone this repo (latest v)
1- Create virtual environment through VENV commands
2- Run : pip install torch==2.3.0+cu118 torchaudio==2.3.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
3- Run : pip install git+https://github.com/SWivid/F5-TTS.git
4- Launch infer_gradio.py (found in infer/)

### ✔️ Expected Behavior

![image](https://github.com/user-attachments/assets/6b048575-6400-4a27-877d-077ce0d4c5c8)

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/30951135-9135-4214-8865-a030c7d4d993)

<img width="641" alt="image" src="https://github.com/user-attachments/assets/f65196cf-b143-4473-a93f-74be818aa218">

**Comment by SWivid** [comment]
maybe you could provide a full screenshot for ❌ Actual Behavior
especially to make sure whether the ref_audio is correctly uploaded

**Comment by FierceJDM** [comment]
This time, i tried it without custom voice, Here's what it gave back :

CMD Log :
```shell
$ py infer_gradio.py
Download Vocos from huggingface charactr/vocos-mel-24khz

vocab :  D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\f5_tts\infer\examples\vocab.txt
token :  custom
model :  C:\Users\azerg\.cache\huggingface\hub\models--SWivid--F5-TTS\snapshots\4dcc16f297f2ff98a17b3726b16f5de5a5e45672\F5TTS_Base\model_1200000.safetensors

D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\components\chatbot.py:237: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style dictionaries with 'role' and 'content' keys.
  warnings.warn(
Starting app...
INFO: Could not find files for the given pattern(s).
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\blocks.py", line 2019, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\blocks.py", line 1566, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 208, in basic_tts
    audio_out, spectrogram_path, ref_text_out = infer(
                                                ^^^^^^
  File "D:\User\F5TTS\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 108, in infer
    ref_audio, ref_text = preprocess_ref_audio_text(ref_audio_orig, ref_text, show_info=show_info)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\f5_tts\infer\utils_infer.py", line 278, in preprocess_ref_audio_text
    aseg = AudioSegment.from_file(ref_audio_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\pydub\audio_segment.py", line 723, in from_file
    stdin_data = file.read()
                 ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'read'
``` 

Interface : 
![image](https://github.com/user-attachments/assets/6d605f0f-b353-427e-a7cf-2ec95612b6cf)

**Comment by FierceJDM** [comment]
With Custom voice file :

CMD Log:
```shell
D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\blocks.py", line 2019, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\blocks.py", line 1566, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 208, in basic_tts
    audio_out, spectrogram_path, ref_text_out = infer(
                                                ^^^^^^
  File "D:\User\F5TTS\F5-TTS\src\f5_tts\infer\infer_gradio.py", line 108, in infer
    ref_audio, ref_text = preprocess_ref_audio_text(ref_audio_orig, ref_text, show_info=show_info)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\f5_tts\infer\utils_infer.py", line 278, in preprocess_ref_audio_text
    aseg = AudioSegment.from_file(ref_audio_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\F5TTS\f5-tts\f5tts\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\Tools\Python_3.11.6\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\User\Tools\Python_3.11.6\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by SWivid** [comment]
you need to provide a reference audio or to record one

you can see in your interface it is blank; it is mandatory for inference in the code logic.
![image](https://github.com/user-attachments/assets/c3d0a9fd-3d36-4b10-9e5a-c6a58f6c7b52)
and you can see in the instruction, there is `Ensure the audio is fully uploaded before generation`

**Comment by FierceJDM** [comment]
That's what i did in the second comment i sent man. I tested with both and showed you both results (and obviously said in the 1st comment that there's a 2nd comment in which an audio ref file has been used) because i do not know at which level the error is happening

**Comment by SWivid** [comment]
@FierceJDM Hi, there could be two possible reasons:

1. missing ffmpeg in system
2. a gradio version with conflict

first we could try install ffmpeg because in cmd output there is `RuntimeWarning: Couldn't find ffprobe or avprobe`
you can download from the official website and add the ffmpeg to system path (there are many tutorial for the installation online)

if still not working, could try lower the gradio version to 4.xx.xx, see if will work

hope will help

**Comment by FierceJDM** [comment]
Hello, i have tried downloading + adding to path ffmpeg. It definitely solved a few problems, but i still don't have any audio being generated + powershell is stuck on `Prefix dict has been built successfully.` :

PS Log : 
```shell
PS D:\User\F5TTS\F5-TTS\src\f5_tts\infer> python infer_gradio.py
Download Vocos from huggingface charactr/vocos-mel-24khz

vocab :  D:\User\Tools\Python_3.11.6\Lib\site-packages\f5_tts\infer\examples\vocab.txt
token :  custom
model :  C:\Users\.cache\huggingface\hub\models--SWivid--F5-TTS\snapshots\4dcc16f297f2ff98a17b3726b16f5de5a5e45672\F5TTS_Base\model_1200000.safetensors

D:\User\Tools\Python_3.11.6\Lib\site-packages\gradio\components\chatbot.py:237: UserWarning: You have not specified a value for the `type` parameter. Defaulting to the 'tuples' format for chatbot messages, but this is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style dictionaries with 'role' and 'content' keys.
  warnings.warn(
Starting app...
INFO: Could not find files for the given pattern(s).
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ref_text   This is before call and this is after call. So we have an elapsed of around 60 minutes or 45 minutes between person, let's just say person A and person B. They're the same person but you guys get the point.
gen_text 0 Hello guys, charlie morgan.
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\AppData\Local\Temp\jieba.cache
Loading model cost 0.973 seconds.
Prefix dict has been built successfully.

Keyboard interruption in main thread... closing server.
PS D:\User\F5TTS\F5-TTS\src\f5_tts\infer>
``` 

I tried every solution in #356 , nothing worked

**Comment by SWivid** [comment]
Try
```
pip install gradio==4.44.1
```

**Comment by FierceJDM** [comment]
I pip installed 4.44.1 and it actually replaced the newer version.
But it is still giving me the same output, stuck on 0.0%
![image](https://github.com/user-attachments/assets/e24a779d-b235-4a21-99ff-897909e2b5fc)

**Comment by SWivid** [comment]
1. make sure the gpu is used
2. use your ide to debug (e.g. vscode), or you could add print to each line of the infer_gradio.py; then you could tell us to which specific line, the inference is stuck at

**Comment by FierceJDM** [comment]
The GPU doesn't seem to be used by powershell when running infer_gradio.py

This is how i added a few prints to the infer() function in infer_gradio.py : 
```python
...
def infer(
    ref_audio_orig, ref_text, gen_text, model, remove_silence, cross_fade_duration=0.15, speed=1, show_info=gr.Info
):
    ref_audio, ref_text = preprocess_ref_audio_text(ref_audio_orig, ref_text, show_info=show_info)
    print("#5#")
    if model == "F5-TTS":
        ema_model = F5TTS_ema_model
    elif model == "E2-TTS":
        global E2TTS_ema_model
        if E2TTS_ema_model is None:
            show_info("Loading E2-TTS model...")
            E2TTS_ema_model = load_e2tts()
        ema_model = E2TTS_ema_model
    elif isinstance(model, list) and model[0] == "Custom":
        assert not USING_SPACES, "Only official checkpoints allowed in Spaces."
        global custom_ema_model, pre_custom_path
        if pre_custom_path != model[1]:
            show_info("Loading Custom TTS model...")
            custom_ema_model = load_custom(model[1], vocab_path=model[2])
            pre_custom_path = model[1]
        ema_model = custom_ema_model
    print("#6#")

    final_wave, final_sample_rate, combined_spectrogram = infer_process(
        ref_audio,
        ref_text,
        gen_text,
        ema_model,
        vocoder,
        cross_fade_duration=cross_fade_duration,
        speed=speed,
        show_info=show_info,
        progress=gr.Progress(),
    )
    print("#7#")
    # Remove silence
    if remove_silence:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".wav") as f:
            sf.write(f.name, final_wave, final_sample_rate)
            remove_silence_for_generated_wav(f.name)
            final_wave, _ = torchaudio.load(f.name)
        final_wave = final_wave.squeeze().cpu().numpy()
    print("#8#")
    # Save the spectrogram
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp_spectrogram:
        spectrogram_path = tmp_spectrogram.name
        save_spectrogram(combined_spectrogram, spectrogram_path)

    print("#9#")
    return (final_sample_rate, final_wave), spectrogram_path, ref_text
...
``` 
This is what it printed out on the shell:
```shell
INFO: Could not find files for the given pattern(s).
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ref_text   This is before call and this is after call. So we have an elapsed of around 60 minutes or 45 minutes between person, let's just say person A and person B. They're the same person but you guys get the point.
#5#
#6#
gen_text 0 Hello guys.
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\AppData\Local\Temp\jieba.cache
Loading model cost 0.950 seconds.
Prefix dict has been built successfully.
```

**Comment by SWivid** [comment]
`The GPU doesn't seem to be used by powershell when running infer_gradio.py`

so how long have you waited if you are runing on cpu? it is possible to take several minutes if not using gpu

1. wait for least 30 minutes
2. check for the right installation of torch+cuda
3. if using amd gpu, search for onnx in issues, using an onnx version that could leverage the amd gpu
