### ISSUE TITLE
macOS Apple M1 Support? Dataset format?

### ISSUE THREAD

**Issue by yukiarimo** [SWivid/F5-TTS#56]
I would like to run this on my MacBook Pro.

Also, does it support the LJSpeech-like dataset format? Can you please provide the Google Colab notebook for both fine-tuning and training from scratch?

**Comment by SWivid** [comment]
May refer to `model/dataset.py`, just with a modified script to do the pre-processing of dataset as in `scripts/`.
also #27

**Comment by ChristianWeyer** [comment]
The test scripts run straight on MPS @yukiarimo - so there is nothing special to do for macOS.
https://github.com/search?q=repo%3ASWivid%2FF5-TTS+mps&type=code

**Comment by ahmetkca** [comment]
@ChristianWeyer 
I am getting the following error:
```
❯ uv run python test_infer_single.py
objc[66897]: Class AVFFrameReceiver is implemented in both /opt/homebrew/Cellar/ffmpeg@6/6.1.2_3/lib/libavdevice.60.3.100.dylib (0x11de68308) and /Users/ahmetkca/Projects/F5-TTS/.direnv/python-3.9/lib/python3.9/site-packages/av/.dylibs/libavdevice.60.3.100.dylib (0x356dc0760). One of the two will be used. Which one is undefined.
objc[66897]: Class AVFAudioReceiver is implemented in both /opt/homebrew/Cellar/ffmpeg@6/6.1.2_3/lib/libavdevice.60.3.100.dylib (0x11de68358) and /Users/ahmetkca/Projects/F5-TTS/.direnv/python-3.9/lib/python3.9/site-packages/av/.dylibs/libavdevice.60.3.100.dylib (0x356dc07b0). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/Users/ahmetkca/Projects/F5-TTS/test_infer_single.py", line 9, in <module>
    from model import CFM, UNetT, DiT, MMDiT
  File "/Users/ahmetkca/Projects/F5-TTS/model/__init__.py", line 7, in <module>
    from model.trainer import Trainer
  File "/Users/ahmetkca/Projects/F5-TTS/model/trainer.py", line 22, in <module>
    from model.dataset import DynamicBatchSampler, collate_fn
  File "/Users/ahmetkca/Projects/F5-TTS/model/dataset.py", line 191, in <module>
    ) -> CustomDataset | HFDataset:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by SWivid** [comment]
@ahmetkca try with current version, mainly for new feature with py310

**Comment by SWivid** [comment]
I'll close this issue, if you have other questions you can reopen this issue.

**Comment by alkeryn** [comment]
@ahmetkca sorry for the bump but can you tell me your experience as compared to openvoice and others ?
thank you !
