### ISSUE TITLE
returned non-zero exit status 1 when run Train data

### ISSUE THREAD

**Issue by CJ468** [SWivid/F5-TTS#583]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Windows 11, Python 3.11

### Steps to Reproduce

Run Train Data with Auto Settings

### ✔️ Expected Behavior

Run Train data

### ❌ Actual Behavior

vocab :  2545
Using logger: tensorboard
Traceback (most recent call last):
  File "C:\F5-TTS\src\f5_tts\train\finetune_cli.py", line 161, in <module>
    main()
  File "C:\F5-TTS\src\f5_tts\train\finetune_cli.py", line 132, in main
    trainer = Trainer(
              ^^^^^^^^
  File "C:\F5-TTS\src\f5_tts\model\trainer.py", line 90, in __init__
    from torch.utils.tensorboard import SummaryWriter
  File "C:\F5-TTS\venv\Lib\site-packages\torch\utils\tensorboard\__init__.py", line 1, in <module>
    import tensorboard
ModuleNotFoundError: No module named 'tensorboard'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\F5-TTS\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\F5-TTS\venv\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "C:\F5-TTS\venv\Lib\site-packages\accelerate\commands\launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "C:\F5-TTS\venv\Lib\site-packages\accelerate\commands\launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\F5-TTS\\venv\\Scripts\\python.exe', 'src/f5_tts/train/finetune_cli.py', '--exp_name', 'F5TTS_Base', '--learning_rate', '1e-05', '--batch_size_per_gpu', '3200', '--batch_size_type', 'frame', '--max_samples', '64', '--grad_accumulation_steps', '1', '--max_grad_norm', '1', '--epochs', '431', '--num_warmup_updates', '900', '--save_per_updates', '1802', '--last_per_steps', '450', '--dataset_name', 'swedish', '--finetune', 'True', '--tokenizer', 'pinyin', '--log_samples', 'True', '--logger', 'tensorboard']' returned non-zero exit status 1.

**Comment by SWivid** [comment]
> import tensorboard
> ModuleNotFoundError: No module named 'tensorboard'

pip install tensorboard

**Comment by CJ468** [comment]
Found the problem, fixed now.
