### ISSUE TITLE
IndexError: too many indices for tensor of dimension 2 while infer with ref text

### ISSUE THREAD

**Issue by NIKITOSOVUI** [SWivid/F5-TTS#592]
### Checks

- [X] This template is only for usage issues encountered.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Windows 10, python 3.11.8, RTX 2060 8GB, torch version: 2.4.0+cu118
I am using this github hash: e3ea8a0c68a218ea27bf012f58a94d0d9a37480e from vid https://www.youtube.com/watch?v=GmketyZW2c4&ab_channel=JarodsJourney
https://github.com/JarodMica/F5-TTS

Settings in App:

![screencapture-127-0-0-1-7860-2024-12-06-11_03_57](https://github.com/user-attachments/assets/ff25f125-de2c-493c-ac3d-7f72ad6e63e7)

![screencapture-127-0-0-1-7860-2024-12-06-11_00_49](https://github.com/user-attachments/assets/3dbf8939-e780-4ec8-b12a-ff058290e602)

![screencapture-127-0-0-1-7860-2024-12-06-11_03_42](https://github.com/user-attachments/assets/241c0283-f3e3-497d-9144-fa9a6f2d8865)

### Steps to Reproduce

1. run venv\Scripts\activate
2. run f5-tts_finetune-gradio
3. Test Model -> Choose latest checkpoint from Train Data (step_30000) -> Random Sample -> Infer

### ✔️ Expected Behavior

Generated audio

### ❌ Actual Behavior

```
D:\Jobs\Jacky Car\goblin\F5-TTS>venv\Scripts\activate

(venv) D:\Jobs\Jacky Car\goblin\F5-TTS>f5-tts_finetune-gradio
Starting app...
ИНФОРМАЦИЯ: не удается найти файлы по заданным шаблонам.
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Fetching 4 files: 100%|██████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]

Size mismatch for transformer.text_embed.text_blocks.0.dwconv.weight: checkpoint torch.Size([512, 7, 1]), model torch.Size([512, 1, 7])

Size mismatch for transformer.text_embed.text_blocks.1.dwconv.weight: checkpoint torch.Size([512, 7, 1]), model torch.Size([512, 1, 7])

Size mismatch for transformer.input_embed.conv_pos_embed.conv1d.0.weight: checkpoint torch.Size([512, 31, 32]), model torch.Size([512, 32, 31])

Size mismatch for transformer.input_embed.conv_pos_embed.conv1d.2.weight: checkpoint torch.Size([512, 31, 32]), model torch.Size([512, 32, 31])
Download Vocos from huggingface charactr/vocos-mel-24khz
D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\vocos\pretrained.py:70: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(model_path, map_location="cpu")

vocab :  D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\..\..\data\goblin_pinyin\vocab.txt
tokenizer :  custom
model :  D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\..\..\ckpts\goblin\model_30000.pt

update >>  None D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\..\..\ckpts\goblin\model_30000.pt True
Converting audio...
Using custom reference text...
gen_text 0 «вовочка, откуда в «буратино» перестройка?» «ну как же?» «вот восьмая страница, третий абзац, первое предложение».
Generating audio in 1 batches...
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\user\AppData\Local\Temp\jieba.cache
Loading model cost 0.475 seconds.
Prefix dict has been built successfully.
  0%|                                                                                            | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\gradio\blocks.py", line 2043, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\gradio\blocks.py", line 1590, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\gradio\utils.py", line 865, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\train\finetune_gradio.py", line 1241, in infer
    tts_api.infer(gen_text=gen_text, ref_text=ref_text, ref_file=ref_audio, nfe_step=nfe_step, file_wave=f.name, speed=speed_slider)
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\api.py", line 118, in infer
    wav, sr, spect = infer_process(
                     ^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\infer\utils_infer.py", line 433, in infer_process
    return infer_batch_process(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\infer\utils_infer.py", line 501, in infer_batch_process
    duration_in_sec = prediction_model(audio, text_list)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\model\modules.py", line 939, in forward
    x = self.transformer(inp, text=text)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\model\modules.py", line 849, in forward
    x = block(x, mask=mask, rope=rope)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\model\modules.py", line 777, in __call__
    attn_output = self.attn(x=norm, mask=mask, rope=rope)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\model\modules.py", line 403, in forward
    return self.processor(self, x, mask=mask, rope=rope)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\src\f5_tts\model\modules.py", line 432, in __call__
    query = apply_rotary_pos_emb(query, freqs, q_xpos_scale)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\torch\amp\autocast_mode.py", line 43, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Jobs\Jacky Car\goblin\F5-TTS\venv\Lib\site-packages\x_transformers\x_transformers.py", line 685, in apply_rotary_pos_emb
    freqs = freqs[:, -seq_len:, :]
            ~~~~~^^^^^^^^^^^^^^^^^
IndexError: too many indices for tensor of dimension 2
```

**Comment by SWivid** [comment]
@NIKITOSOVUI try with the lastest version here

**Comment by NIKITOSOVUI** [comment]
@SWivid Will I be able to use existing checkpoints?

**Comment by SWivid** [comment]
`f5-tts_infer-gradio`
custom
fill in your ckpt & vocab path

**Comment by NIKITOSOVUI** [comment]
Thank you, it works perfectly!

**Comment by rslosch** [comment]
> `f5-tts_infer-gradio` custom fill in your ckpt & vocab path

I believe I am running into a similar issue. I am on runpod and using --share for the gradio. I do not see a "custom" option in gradio UI to select my ckpt & vocab path.

Where can I select the custom finetuned ckpt?

<img width="509" alt="Screenshot 2024-12-06 at 16 32 37" src="https://github.com/user-attachments/assets/9fdf02b2-82c6-4c08-80c4-dadaca64c9be">

**Comment by SWivid** [comment]
@rslosch pull the latest version

**Comment by rslosch** [comment]
> @rslosch pull the latest version

The version was up to date.
I ended up just doing a fresh install using this repo with python 3.10 and cuda 11.8 instead of the recommended setup from the youtube video ( https://www.youtube.com/watch?v=GmketyZW2c4&ab_channel=JarodsJourney). 
Everything is working as expected now. Thx
