### ISSUE TITLE
ImportError: cannot import name 'builder' from 'google.protobuf.internal' on startup

### ISSUE THREAD

**Issue by Vektor369** [SWivid/F5-TTS#603]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

Windows 10, Python 3.10.9, Gradio 5.7.0

### Steps to Reproduce

Create virtual environment by running the command python -m venv venv
Activate environment by running the command python -m venv venv
Run command f5-tts_finetune-gradio

### ✔️ Expected Behavior

The program to start.

### ❌ Actual Behavior

Just went to try again today, and got this:

```
Traceback (most recent call last):
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\Scripts\f5-tts_finetune-gradio.exe\__main__.py", line 4, in <module>
    from f5_tts.train.finetune_gradio import main
  File "F:\AI\F5\F5-TTS\src\f5_tts\train\finetune_gradio.py", line 29, in <module>
    from cached_path import cached_path
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\site-packages\cached_path\__init__.py", line 13, in <module>
    from ._cached_path import cached_path
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\site-packages\cached_path\_cached_path.py", line 15, in <module>
    from .schemes import (
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\site-packages\cached_path\schemes\__init__.py", line 3, in <module>
    from .gs import GsClient
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\site-packages\cached_path\schemes\gs.py", line 8, in <module>
    from google.api_core.exceptions import NotFound
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\site-packages\google\api_core\exceptions.py", line 29, in <module>
    from google.rpc import error_details_pb2
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\site-packages\google\rpc\error_details_pb2.py", line 23, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\jimmy\AppData\Local\Programs\Python\Python310\lib\site-packages\google\protobuf\internal\__init__.py)
```

**Comment by ZhikangNiu** [comment]
https://github.com/protocolbuffers/protobuf/issues/9778

**Comment by Vektor369** [comment]
Thanks. What protobuf version do I install?

**Comment by Vektor369** [comment]
Didn't work for me. I'm still getting "ImportError: cannot import name 'builder' from 'google.protobuf.internal'".
I did the following:
```
pip install protobuf==3.19.6
pip install googleapis-common-protos==1.56.0
```

**Comment by ZhikangNiu** [comment]
![image](https://github.com/user-attachments/assets/c7c08470-6c94-4072-aa04-beb88d60c573)

**Comment by ZhikangNiu** [comment]
actually I think you can use Dockerfile

**Comment by Vektor369** [comment]
> pip install googleapis-common-protos==1.56.0

After trying this, when I click "Transcribe", I get the following in the console:
```
config.json: 100%|████████████████████████████████████████████████████████████████████████| 1.26k/1.26k [00:00<?, ?B/s]
model.safetensors: 100%|██████████████████████████████████████████████████████████| 1.62G/1.62G [01:54<00:00, 14.1MB/s]
generation_config.json: 100%|█████████████████████████████████████████████████████████████| 3.77k/3.77k [00:00<?, ?B/s]
tokenizer_config.json: 100%|████████████████████████████████████████████████████████| 283k/283k [00:00<00:00, 2.90MB/s]
vocab.json: 100%|█████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 8.50MB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████| 2.71M/2.71M [00:00<00:00, 14.7MB/s]
merges.txt: 100%|███████████████████████████████████████████████████████████████████| 494k/494k [00:00<00:00, 13.7MB/s]
normalizer.json: 100%|████████████████████████████████████████████████████████████| 52.7k/52.7k [00:00<00:00, 52.6MB/s]
added_tokens.json: 100%|██████████████████████████████████████████████████████████████████| 34.6k/34.6k [00:00<?, ?B/s]
special_tokens_map.json: 100%|████████████████████████████████████████████████████| 2.19k/2.19k [00:00<00:00, 2.18MB/s]
preprocessor_config.json: 100%|███████████████████████████████████████████████████████████████| 340/340 [00:00<?, ?B/s]
Device set to use cuda
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
```
And this in the gui:
```
transcribe complete samples : 0
path : F:\AI\F5\F5-TTS\src\f5_tts\..\..\data\Kari1_pinyin\wavs
error files : 129
```

Does it have the wrong path? That path doesn't exist. The path to the wavs folder would just be: F:\AI\F5\F5-TTS\data\Kari1_pinyin\wavs

**Comment by Jorvan758** [comment]
> transcribe complete samples : 0

Did you solve it? I'm also getting this message 🤔
