### ISSUE TITLE
The size of tensor a (512) must match the size of tensor b (521) at non-singleton dimension 2

### ISSUE THREAD

**Issue by WGS-note** [SWivid/F5-TTS#635]
### Checks

- [X] This template is only for bug reports, usage problems go with 'Help Wanted'.
- [X] I have thoroughly reviewed the project documentation but couldn't find information to solve my problem.
- [X] I have searched for existing issues, including closed ones, and couldn't find a solution.
- [X] I confirm that I am using English to submit this report in order to facilitate communication.

### Environment Details

torch                         2.3.0

### Steps to Reproduce

我的运行代码：

```python
f5-tts_infer-cli \
--model "F5-TTS" \
--ref_audio "/home/wangguisen/projects/tts/test_audio/wgs-f5tts_test.wav" \
--ref_text "那到时候再给你打电话，麻烦你注意接听。" \
--gen_text "这点请您放心，估计是我的号码被标记了，请问您是XX吗？" \
--vocoder_name "vocos" \
--load_vocoder_from_local \
--ckpt_file "/home/wangguisen/projects/tts/F5-TTS/ckpts/F5TTS_Base/model_1200000.pt" \
--remove_silence false \
--speed 1.0 \
--output_dir "/home/wangguisen/projects/tts/test_audio/output" \
--output_file "wgs_out.wav"
```

### ✔️ Expected Behavior

之前的代码并没有问题，但是我重新pull后就出现了这个问题

### ❌ Actual Behavior

报错：

```shell
Traceback (most recent call last):
  File "/home/wangguisen/miniconda3/envs/f5_tts/bin/f5-tts_infer-cli", line 8, in <module>
    sys.exit(main())
  File "/home/wangguisen/projects/tts/F5-TTS/src/f5_tts/infer/infer_cli.py", line 223, in main
    main_process(ref_audio, ref_text, gen_text, ema_model, mel_spec_type, remove_silence, speed)
  File "/home/wangguisen/projects/tts/F5-TTS/src/f5_tts/infer/infer_cli.py", line 203, in main_process
    audio, final_sample_rate, spectragram = infer_process(
  File "/home/wangguisen/projects/tts/F5-TTS/src/f5_tts/infer/utils_infer.py", line 384, in infer_process
    return infer_batch_process(
  File "/home/wangguisen/projects/tts/F5-TTS/src/f5_tts/infer/utils_infer.py", line 469, in infer_batch_process
    generated_wave = vocoder.decode(generated_mel_spec)
  File "/home/wangguisen/miniconda3/envs/f5_tts/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wangguisen/miniconda3/envs/f5_tts/lib/python3.10/site-packages/vocos/pretrained.py", line 112, in decode
    x = self.backbone(features_input, **kwargs)
  File "/home/wangguisen/miniconda3/envs/f5_tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wangguisen/miniconda3/envs/f5_tts/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangguisen/miniconda3/envs/f5_tts/lib/python3.10/site-packages/vocos/models.py", line 80, in forward
    x = self.norm.weight.data * x / torch.norm(x, p=2, dim=1, keepdim=True) + self.norm.bias.data
RuntimeError: The size of tensor a (512) must match the size of tensor b (521) at non-singleton dimension 2
```

**Comment by WGS-note** [comment]
我重新构建了Conda环境，已解决。

**Comment by SWivid** [comment]
@WGS-note 解决了就好~

note：
新更新的版本里`--remove_silence`也变成store_true了
如果toml里没有设置true或者不传，默认就是false，和`--load_vocoder_from_local`一样了
