### ISSUE TITLE
Error when installing dependencies on Mac

### ISSUE THREAD

**Issue by ahmetkca** [SWivid/F5-TTS#69]
```
Using Python 3.10.0 environment at .direnv/python-3.10
Resolved 142 packages in 36ms
error: Failed to prepare distributions
  Caused by: Failed to fetch wheel: llvmlite==0.36.0
  Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1)

[stderr]
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/Users/ahmetkca/.cache/uv/builds-v0/.tmpxYn69B/lib/python3.10/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=[])
  File "/Users/ahmetkca/.cache/uv/builds-v0/.tmpxYn69B/lib/python3.10/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
    self.run_setup()
  File "/Users/ahmetkca/.cache/uv/builds-v0/.tmpxYn69B/lib/python3.10/site-packages/setuptools/build_meta.py", line 503, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/Users/ahmetkca/.cache/uv/builds-v0/.tmpxYn69B/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 55, in <module>
  File "<string>", line 52, in _guard_py_ver
RuntimeError: Cannot install on Python version 3.10.0; only versions >=3.6,<3.10 are supported.
```

**Comment by SWivid** [comment]
maybe 
```
pip install -U numba
pip install -U llvmlite
```
or try with python 3.9

**Comment by ahmetkca** [comment]
> maybe 
> 
> ```
> 
> pip install -U numba
> 
> pip install -U llvmlite
> 
> ```
> 
> or try with python 3.9
> 
> 

We can close this issue. It has nothing to do with anything in the repo. I used uv to install packages and it happens to have a problem building llvmlite with python >3.10

**Comment by SWivid** [comment]
@ahmetkca sure, hope it goes well now
