### ISSUE TITLE
vocos = Vocos.from_pretrained("charactr/vocos-mel-24khz")

### ISSUE THREAD

**Issue by 397688551** [SWivid/F5-TTS#92]
My server can not access huggingface, resulting in the use of this model can not download, is there any other way, such as first download to the local load, is there such a code function

python inference-cli.py --model "E2-TTS" --ref_audio "tests/ref_audio/test_zh_1_ref_short.wav" --ref_text "对，这就是我，万人敬仰的太乙真人。" --gen_text "突然，身边一阵笑声。我看着他们，意气风发地挺直了胸膛，甩了甩那稍显肉感的双臂，轻笑道，我身上的肉，是为了掩饰我爆棚的魅力，否则，岂不吓坏了你们呢？"

vocos = Vocos.from_pretrained("charactr/vocos-mel-24khz")

Traceback (most recent call last):
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/connectionpool.py",line 789, in urlopen
    response = self._make_request(
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/connectionpool.py",line 490, in _make_request
    raise new_e
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/connectionpool.py",line 466, in _make_request
    self._validate_conn(conn)
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/connectionpool.py",line 1095, in _validate_conn
    conn.connect()
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f864f36f550>, 'Connection to huggingface.co timed out. (connect timeout=10)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/requests/adapters.py", line667, in send
    resp = conn.urlopen(
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/connectionpool.py",line 843, in urlopen
    retries = retries.increment(
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /charactr/vocos-mel-24khz/resolve/main/config.yaml (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f864f36f550>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 395, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/requests/sessions.py", line589, in request
    resp = self.send(prep, **send_kwargs)
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/requests/sessions.py", line703, in send
    r = adapter.send(request, **kwargs)
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/requests/adapters.py", line688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /charactr/vocos-mel-24khz/resolve/main/config.yaml (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f864f36f550>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 313255c3-6abd-484c-afb9-c298d779a5ff)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/aistudio/workspace/task/F5-TTS/inference-cli.py", line 99, in <module>
    vocos = Vocos.from_pretrained("charactr/vocos-mel-24khz")
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/vocos/pretrained.py", line 67, in from_pretrained
    config_path = hf_hub_download(repo_id=repo_id, filename="config.yaml", revision=revision)
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/aistudio/workspace/system-default/envs/f5/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1826, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file onthe Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by ZhikangNiu** [comment]
Sure, you can download vocos checkpoint and change some vocos source code to load local checkpoint.
You can check this issue: https://github.com/gemelo-ai/vocos/issues/32

**Comment by 397688551** [comment]
Useful, thank you

**Comment by ZhikangNiu** [comment]
I will close this issue. If you have other questions, you can reopen this issue.

**Comment by Liangzi-qyh** [comment]
Hello, I encountered the same problem as you, because the cloud server cannot directly access HuggingFace, so when executing the python gradio_app.py, it will report the same error as you, what do I need to modify in the untils_infer.py

**Comment by GiveMeSunShine** [comment]
modify python3.10/site-packages/vocos/pretrained.py
<img width="1760" alt="image" src="https://github.com/user-attachments/assets/71909e5a-1f28-49cc-85dd-3692ccffac94">
